FORMAT: 1A
HOST: http://polls.apiblueprint.org/

FORMAT: 1A
HOST: https://pracevcr.cz/api2/

# Český Trh Práce s.r.o.
This API demonstrates functionality of real server API for Recruitis app.
There are 4 groups with own actions - candidates, jobs, interviews and newsfeed.


#CHANGELOG

##1.1.0
 - Přidáno volání `GET` jobs/{id}/customflow pro testování inzerátů s dynamickým flow 
 - Přidáno volání `GET` jobs/customflow pro testování inzerátů s dynamickým flow 

##0.9.9 beta 3
 - U volání `GET` `answers/` přibyly tyto parametry: `agreement_status` a `agreement_reason`

##0.9.9 beta 2
 - Přidáno volání `GET` `answers/{id}/questionnaire`
 - Odstraněno volání `GET` `candidates/{candidate_id}/questionnaire`

##0.9.9 beta
 - Bylo přidáno volání `interview/`
 - U volání `interview` změněna položka `interview_date` na `date_from`
    - Přidána položka `date_to`
    - Přidána položka `answer_id`
 - Volání `email/send` bylo přejmenováno na `messages/send/email` 
 - Volání `email/template/{id}` bylo přejmenováno na `messages/template/email/{id}` 
 - Bylo přidáno volání `messages/send/sms` 
 - Bylo přidáno volání `messages/template/sms` 
 - Bylo přidáno volání `answers/{id}/flow/{value}` 
 - Bylo přidáno volání `answers/{id}/rating/{value}` 
 - Odstraněno volání `candidates/{candidate_id}/comments` , namísto něj použivat `comments/`

##0.9.8 beta
 - Přidáno volání `comments/` (GET,POST,PUT)
 - Přidáno volání `email/templates/`
 - Do `GET` `jobs/` byl přidán parametr `flow_answers` 
 - Do `GET` `answers/` byl přidán parametr `flowid` 
 - Upravena historie pro kandidáta: Nyní to je `newsfeed/{?candidateid,limit,page}`
 - Změny u historie kandidáta: 
    - `date_time` : nyní je `date_created`
    - `action_type` : nyní je `icon`
    - Celé pole `history` bylo dáno o řád výše - přímo do `payload`.
    - `candidate_id`, které bylo ihned v `payload` vedle `history` pole se nyní vztahuje ke každému prvku v `payload`

##0.4
 - U volání `/newsfeed` byla zrušen parametr "source_site" a "type". 
 Parametr "date_time" upraven na "date_created",
 parametr "personalist" změněn na "author" a přidán atribut "author_id"

##0.3
 - Přidán "channel" element do api callu "jobs"
 - candidates{candidate_id} přejmenováno na answers/id
 - U answers/{id} a answers/ byl prvek "first_response_date" přejmenován na date_response
 - U answers/{id} byl cv_path změněn na attachments

##0.2
 - GET `jobs/` byl změnen element `created_date` na `date_created`
 - Přidáno volání `email/send`

##0.1
 - Počáteční verze


#TODO
dodělat tyto API:

 - Dotazník :)
 - Zamyslet se nad error handlerem. message_localize neni implementovan
 
 SESSIONMANAGER - callback on after call destruct session! at se nic neposila zpet do CLI!
 

#Group Authentication

## Login [/login]

### Login [POST]

Login request for user authentication. Default response is 200. 

 - `device_id` je ID vygenerováno firebase službou od Google inc. Pokud systém obrdží tento parametr,
 umožní přes tento login posílat SMS zprávy a systém počítá s tím, že se jedná o mobilní aplikaci.
- `device_name` je pouze označení daného api spojení. Pod tímto názvem ho pak uživatel uvidí v Recruitisu. Jednou,
jak se device_name zapíše, nelze přes API volání změnit. Lze změnit pouze v systému Recruitis.


+ Request 

        {
            "password":"heslo",
            "username":"user@test.cz",
            "device_id": "efee4554959cecejo",
            "device_name": "Samsung S8",
            
        }
        
+ Response 200 (application/json)

        {
            "payload": {
                "token": "68b0c063374ac7fe0abaa18342dbad23168876a1.8699.3e398f0ccd4c857b29de10397534afac",
                "device_id": "x56sj64uzr4we64rtb489uzjj186drgv13e",
                "device_name": "restapiklient"
            },
            "meta": {
                "duration": "2259.39",
                "total_duration": 2300,
                "code": 200,
                "message": "",
                "message_localized": "Přihlášení proběhlo v pořádku"
            }
        }
        
+ Response 404 (application/json)

        {
            "payload": null,
            "meta": {
                "duration": "139.58",
                "total_duration": 440,
                "code": 404,
                "message": "Login failed (#4000)",
                "message_localized": "Vložené údaje nesouhlasí"
            }
        }
        
#Group Me

## My account information [/me]

### Me [GET]

Získání informací o mém účtu, za kterého jsem právě přihlášen

+ Request
    + Headers

            Authorization: Bearer 68b0c063374ac7fe0abaa18342dbad23168876a1.8699.3e398f0ccd4c857b29de10397534afac

+ Response 200 (application/json)

        {
            "payload": {
                "fullname": "Michal Macinka",
                "email": "macinka@gmail.com",
                "img_src": "http://lide.uhk.cz/fim/student/macinmi1/avatar_2.jpg",
                "device_id": "x56sj64uzr4we64rtb489uzjj186drgv13e",
                "device_name": "restapiklient"
            },
            "meta": {
                "duration": "2259.39",
                "total_duration": 2300,
                "code": 200,
                "message": "",
                "message_localized": "OK"
            }
        }

+ Response 401 (application/json)

        {
            "payload": null,
            "meta": {
                "duration": "139.58",
                "total_duration": 440,
                "code": 404,
                "message": "Musíte být přihlášen",
            }
        }

# Group Answers
API calls for actions connected with answers.

## Answers List [/answers{?limit,page,search,jobid,flowid}]

Seznam všech došlých odpovědí k dané firmě
 
### Get All Answers [GET]

+ Request
    + Headers

            Authorization: Bearer 68b0c063374ac7fe0abaa18342dbad23168876a1.8699.3e398f0ccd4c857b29de10397534afac

+ Parameters
    + limit (optional,numeric,`10`) - pocet entit, ktere se maji zobrazit
    + page (optional,numeric,`1`) - strana s vypisem odpovedi
    + search (optional,string) - Vyhledávání ve jméně
    + jobid (optional,int) - Omezení na určitý inzerát
    + flowid (optional,int) - Filtrace podle konkrétního flow

+ Response 200 (application/json)

        {
            "payload":
                [
                    {
                        "candidate_id": 1,
                        "answer_id": 1,
                        "job_id": 123456,
                        "name": {
                            "first_name": "Michal",
                            "last_name": "Macinka",
                            "initials": "MM"
                        },
                        "title": {
                            "before": null,
                            "after": null
                        },
                        "user_img": "http://lide.uhk.cz/fim/student/macinmi1/avatar_2.jpg",
                        "rating": 4,
                        "signup_job": {
                            "job_title": "Android Developer",
                            "job_source_site": "PRACEvIT.cz"
                        },
                        "date_response": "18.02.17 17:31",
                        "phone": "666777888",
                        "flow_id": 4,
                        "rejected": false,
                        "agreement_status": null,
                        "agreement_reason": false,
                        "source_site": "PRACEvCR.cz"
                    },
                    {
                        "candidate_id": 2,
                        "answer_id": 2,
                        "job_id": 123456,
                        "name": {
                            "first_name": "Karel",
                            "last_name": "Nový",
                            "initials": "KN"
                        },
                        "title": {
                            "before": "Ing.",
                            "after": null
                        },
                        "user_img": null,
                        "rating": 2,
                        "signup_job": {
                            "job_title": "Android Developer",
                            "job_source_site": "PRACEvIT.cz"
                        },
                        "date_response": "19.02.17 15:42",
                        "phone": "777888777",
                        "flow_id": 1,
                        "rejected": false,
                        "agreement_status": null,
                        "agreement_reason": false,
                        "source_site": "PRACEvCR.cz"
                    },
                    {
                        "candidate_id": 3,
                        "answer_id": 3,
                        "job_id": 123456,
                        "name": {
                            "first_name": "Libor",
                            "last_name": "Souček",
                            "initials": "LS"
                        },
                        "title": {
                            "before": "Mgr.",
                            "after": "Ph.D."
                        },
                        "user_img": "http://pracevcr.cz/upload/employees/-/1.jpg",
                        "rating": 123456,
                        "signup_job": {
                            "job_title": "Android Developer",
                            "job_source_site": "PRACEvIT.cz"
                        },
                        "date_response": "21.02.17 07:32",
                        "phone": "111222333",
                        "flow_id": 3,
                        "rejected": false,
                        "agreement_status": 1,
                        "agreement_reason": "Souhlas byl přijat",
                        "source_site": "PRACEvCR.cz"
                    },
                    {
                        "candidate_id": 4,
                        "job_id": 123456,
                        "name": {
                            "first_name": "Jiří",
                            "last_name": "Koral",
                            "initials": "JK"
                        },
                        "title": {
                            "before": null,
                            "after": "DiS."
                        },
                        "user_img": "http://pracevcr.cz/upload/employees/-/5.jpg",
                        "rating": 5,
                        "signup_job": {
                            "job_title": "Android Developer",
                            "job_source_site": "PRACEvIT.cz"
                        },
                        "first_response_date": "21.02.17 07:30",
                        "phone": "111222444",
                        "flow_id": 4,
                        "rejected": false,
                         "agreement_status": 0,
                        "agreement_reason": "",
                        "source_site": "PRACEvCR.cz"
                    },
                    {
                        "candidate_id": 5,
                        "answer_id": 5,
                        "job_id": 123456,
                        "name": {
                            "first_name": "Jiří",
                            "last_name": "Mladý",
                            "initials": "JM"
                        },
                        "title": {
                            "before": "Mgr.",
                            "after": null
                        },
                        "user_img": null,
                        "rating": 4,
                        "signup_job": {
                            "job_title": "Android Developer",
                            "job_source_site": "PRACEvIT.cz"
                        },
                        "date_response": "20.02.17 23:30",
                        "phone": "222555888",
                        "flow_id": 5,
                        "rejected": false,
                        "agreement_status": -1,
                        "agreement_reason": "uchazeč zamítl tuto pozici",
                        "source_site": "PRACEvCR.cz"
                    },
                    {
                        "candidate_id": 6,
                        "answer_id": 6,
                        "job_id": 123456,
                        "name": {
                            "first_name": "Tomáš",
                            "last_name": "Tichý",
                            "initials": "TT"
                        },
                        "title": {
                            "before": "",
                            "after": ""
                        },
                        "user_img": "http://pracevcr.cz/upload/employees/-/0.jpg",
                        "rating": 0,
                        "signup_job": {
                            "job_title": "Android Developer",
                            "job_source_site": "PRACEvIT.cz"
                        },
                        "date_response": "17.02.17 17:31",
                        "phone": "999999991",
                        "flow_id": 0,
                        "rejected": true,
                        "agreement_status": null,
                        "agreement_reason": null,
                        "source_site": "PRACEvCR.cz"
                    },
                    {
                        "candidate_id": 7,
                        "answer_id": 7,
                        "job_id": 123456,
                        "name": {
                            "first_name": "Lukáš",
                            "last_name": "Kabeláč",
                            "initials": "LK"
                        },
                        "title": {
                            "before": null,
                            "after": null
                        },
                        "user_img": null,
                        "rating": 3,
                        "signup_job": {
                            "job_title": "Android Developer",
                            "job_source_site": "PRACEvCR.cz"
                        },
                        "date_response": "29.06.17 10:38",
                        "phone": "999999992",
                        "flow_id": 6,
                        "rejected": false,
                         "agreement_status": null,
                        "agreement_reason": null,
                        "source_site": "PRACEvCR.cz"
                    },
                    {
                        "candidate_id": 8,
                        "answer_id": 8,
                        "job_id": 123456,
                        "name": {
                            "first_name": "Lukáš",
                            "last_name": "Kabeláč",
                            "initials": "LK"
                        },
                        "title": {
                            "before": null,
                            "after": null
                        },
                        "user_img": null,
                        "rating": 0,
                         "agreement_status": null,
                        "agreement_reason": null,
                        "signup_job": {
                            "job_title": "Úklidový pracovník v obrovském nadnárodním korporátu: milióny benefitů ve formě tužek na psaní (všechny mají ulomený hrot, takže jsou úplně k ničemu, ale no neber to); práce 43h denně, kde budeš neustále ve stresu a navíc prakticky skoro vůbec neplacená; ale máme tu kafe zadarmo, samozřejmě pro zaměstnance po zkušebce; tady prostě chceš pracovat a neboj, my ti tu možnost nabídneme a jako bonus tě sedřem z kůže, pošli CVčko ;)",
                            "job_source_site": "PRACEvHRADCI.cz"
                        },
                        "date_response": "07.07.17 17:22",
                        "phone": "999999992",
                        "flow_id": 0,
                        "rejected": false,
                        "source_site": "PRACEvCR.cz"
                    }
                ],
            "meta": 
                {
                    "entries_from": 1,
                    "entries_to": 10,
                    "entries_total": 50,
                    "code": 200,
                    "message": "OK"
                }
        }
        
+ Response 404 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 404,
                    "message": "The resource you're looking for doesn't exist."
                }
        }
    

## Answers Detail [/answers/{id}]

Detail konkrétní odpovědi.
Vysvětlení parametru `agreement_status` a `agreement_reason` :

    - `agreement_status`: Jedná se o informaci, jestli je daný uchazeč zkopírován a čeká na schválení, nebo danou nabídku
    pozice již zamítl. Může nabývat hodnot null,0,1,-1.
    
        NULL: Zadaný člověk nebyl zkopírován a nemusí čekat na žádné schválení
        0: Zadaný člověk čeká na vyjádření. V tuto chvíli je zakázané provádět s ním jakékoli pohovorové operace.
        1: Zadaný člověk schválil zkopírování na konkrétní pozici.
        -1: zadaný člověk zamítl danou pozici. V tuto chvíli je zakázané provádět s ním jakékoli pohovorové operace.
        
- `agreement_reason`: Pokud `agreement_status` nabývá hodnoty 1 nebo -1, poté je zde řečen důvod schválení / zamítnutí.

flow_id: 
<br/>
<code>
    NOVY / NEW = 0; <br/>
    VE VYBERU / IN_SELECTION = 1; <br/>
    TELEFON / PRE_SCREENING = 3; <br/>
    POHOVOR / INTERVIEW = 4; <br/>
    VYBRAN / SELECTED = 5; <br/>
    PRIJAT / ACCEPTED = 6; <br/>
</code>


rejected:
<br/>
<code>
    0 //not rejected    
    1 //rejected    
</code>

### Get Answer Detail [GET]
+ Parameters
    + id (required, number, `1`) - Answer id

+ Response 200 (application/json)

        {
            "payload":
                {
                    "candidate_id": 1,
                    "name": {
                        "first_name": "Michal",
                        "last_name": "Macinka",
                        "initials": "MM"
                    },
                    "title": {
                        "before": null,
                        "after": null
                    },
                    "user_img": "http://lide.uhk.cz/fim/student/macinmi1/avatar_2.jpg",
                    "email": null,
                    "phone": null,
                    "sign_job": {
                        "job_title": "Android Developer",
                        "job_source_site": "PRACEvCR.cz"
                    },
                    "flow_id": 4,
                    "rejected": false,
                    "rating": 4,
                    "agreement_status": -1,
                    "agreement_reason": "uchazeč zamítl tuto pozici",
                    "interview_date": "21.02.17 09:30",
                    "date_response": "18.02.17 17:31",
                    "attachments": [
                        {
                        "url": "https://pracevcr.cz/upload/attachments/-/9d2ef6f7cde1ca66dec745f155ec77c6.html",
                        "name": "Systémový email - profesia.sk"
                        },
                        {
                        "url": "https://pracevcr.cz/upload/cv/-/8d66585d613a15c50b4c279043d1af47.pdf",
                        "name": "PROFESIASKCV2257959sk.pdf"
                        },
                        {
                        "url": "https://pracevcr.cz/upload/cv/-/6e8bed5384f4eccf961fcb22cd97c956.txt",
                        "name": "suhlasosobneudaje.txt"
                        }
                    ],
                    "cover_letter": ""
                },
            "meta": 
                {
                    "code": 200,
                    "message": "OK"
                }
        }
        

+ Response 404 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 404,
                    "message": "Candidate with {candidate_id} doesn't exists."
                }
        }
       
        
## Modify Answer flow [/answers/{id}/flow/{value}]

Modifikuje fázi výběru dané odpovědi.

####Vysvětlění flow hodnot

| Flow ID | Vysvětlení          | Poznámka |
|:-------|----------------------|----------------------|
| `0`    | Status "Nový"          |
| `1`    | Status "Nepřiřazený"   |
| `2`    | Status "Další kolo"    | Toto ID se momentálně nepoužívá |
| `3`    | Status "Telefon"        |
| `4`    | Status "Pohovor"         |
| `5`    | Status "Vybrán"          |
| `6`    | Status "Přijat"          |
| `8`    | Status "Smazán"          | Toto ID zapřičiní, že daný uchazeč z odpovědi zmizí. |


### Modify Answer Flow [PUT]

+ Parameters
    + id (required, number, `1`) - Answer id
    + value (required, number, `1`) - Flow id : číslo od 0 do 8

+ Response 200 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 200,
                    "message": "OK"
                }
        }
        

+ Response 404 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 404,
                    "message": "Answer doesnt found."
                }
        }
    
    
## Modify Answer rating [/answers/{id}/rating/{value}]

Upraví hodnocení dané odpovědi. Hodnota `value` může nabývat hodnot 0 až 5.


### Modify Answer Rating  [PUT]

+ Parameters
    + id (required, number, `1`) - Answer id
    + value (required, number, `1`) - Flow id : číslo od 0 do 5

+ Response 200 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 200,
                    "message": "OK"
                }
        }
        

+ Response 404 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 404,
                    "message": "Answer doesn't found."
                }
        }
        
## Reject answer [/answers/{id}/reject]

Zařadí danou odpověď do odmítnutých


### Reject Answer  [PUT]

+ Parameters
    + id (required, number, `1`) - Answer id

+ Response 200 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 200,
                    "message": "OK"
                }
        }
        

+ Response 404 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 404,
                    "message": "Answer doesn't found."
                }
        }
        
## Accept answer [/answers/{id}/reject]

Znovu zařadí odpověď mezi aktivní.


### Reject Answer  [PUT]

+ Parameters
    + id (required, number, `1`) - Answer id

+ Response 200 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 200,
                    "message": "OK"
                }
        }
        

+ Response 404 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 404,
                    "message": "Answer doesn't found."
                }
        }
        
## Answer Questionaire [/answers/{id}/questionaire]

### Get All Q&A for Specific Answer [GET]

+ Parameters
    + id (required, number, `1`) - Answer id

+ Response 200 (application/json)

        {
            "payload":[
                {
                    "question": "Je něco, co jsme uváděli v inzerátu, že požadujeme a nejste si jistý/á, zda byste to zvládl/a? Do jaké míry?",
                        "answer": null,
                        "multiple_answers": [
                            {
                                "answer": "Ne",
                                "selected": false
                            }, 
                            {
                                "answer": "Ano",
                                "selected": true
                            },
                            {
                                "answer": "Nevím",
                                "selected": false
                            }
                        ]
                    },
                    {
                        "question": "Odkud jste se o nabídce práce doslechli?",
                        "answer": "Facebook",
                        "multiple_answers": null
                    },
                    {
                        "question": "Jaké je Vaše nejvyšší dosažené vzdělání?",
                        "answer": "VŠ",
                        "multiple_answers": null
                    },
                    {
                        "question": "Jaká je Vaše představa hrubé mzdy?",
                        "answer": "25 tisíc",
                        "multiple_answers": null
                    }
                }
            ],
            "meta": 
                {
                    "code": 200,
                    "message": "OK"
                }
        }
        
+ Response 404 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 404,
                    "message": "Questionnaire doesn't exists."
                }
        }
        
## Candidate History [/newsfeed/{?limit,page,candidate_id}]

### Get All History for Specific Candidate [GET]

+ Parameters
    + candidate_id (required, number, `1`) - Candidate id
    + limit (optional,numeric,`10`) - pocet entit, ktere se maji zobrazit
    + page (optional,numeric,`1`) - strana s vypisem odpovedi

+ Response 200 (application/json)

        {
            "payload":
            {
                "newsfeed_id": "260824",
                "candidate_id": "235616",
                "user_img": null,
                "date_created": "2017-08-25 10:58:19",
                "action_content": "Byl změněn stav uchazeče <strong>Mirek Pílek3</strong> na <strong>pre-screening</strong> u inzerátu <strong>Testovací pozice - Hledáme pracovnici úklidu</strong>.",
                "icon": "icon-directions",
                "attachments": [],
                "personalist": "Jiří Landovský",
                "personalist_id": "8784",
                "name": {
                    "first_name": "Jiří",
                    "last_name": "Landovský",
                    "initials": "JL"
                },
                "title": {
                    "before": null,
                    "after": null
                }
            },
        
        
            "payload_old":
                {
                    "candidate_id": 1,
                    "history": [
                        {
                            "history_id": 1,
                            "author": null,
                            "date_time": "21.06.17 14:22",
                            "action_type": "icon-bubble",
                            "action_content": "Uchazeč <strong>Will Smith</strong> byl přidán přes systémový email do inzerátu <strong>Pracovník/ce úklidu</strong>"
                        },
                        {
                            "history_id": 2,
                            "author": "Tereza Barková",
                            "date_time": "21.06.17 14:25",
                            "action_type": "icon-directions",
                            "action_content": "Byl změněn stav uchazeče <strong>Will Smith</strong> na <strong>pre-screening</strong> u inzerátu <strong>Pracovník/ce úklidu</strong>."
                        },
                        {
                            "history_id": 3,
                            "author": "Tereza Barková",
                            "date_time": "21.06.17 14:31",
                            "action_type": "icon-briefcase",
                            "action_content": "Byla naplánovaná schůzka s Will Smith v 20.07.2017 11:00"
                        },
                        {
                            "history_id": 4,
                            "author": "Tereza Barková",
                            "date_time": "21.06.17 14:32",
                            "action_type": "icon-envelope",
                            "action_content": "Uchazečovi byla odeslána zpráva s pozváním na pohovor."
                        },
                        {
                            "history_id": 5,
                            "author": "Štěpán Bartyzal",
                            "date_time": "11.07.17 12:41",
                            "action_type": "icon-trash",
                            "action_content": "Uchazeč <strong>Will Smith</strong> byl odstraněn z inzerátu <strong>Pracovník/ce úklidu</strong>."
                        },
                        {
                            "history_id": 6,
                            "author": "Tereza Barková",
                            "date_time": "11.07.17 14:31",
                            "action_type": "icon-envelope",
                            "action_content": "Uchazečovi byla odeslána zpráva \"Připomenutí nabídky pracovní pozice\"."
                        },
                        {
                            "history_id": 7,
                            "author": "Tereza Barková",
                            "date_time": "11.07.17 14:31",
                            "action_type": "icon-action-redo",
                            "action_content": "Uchazeč <strong>Will Smith</strong> byl přiřazen k inzerátu <strong>Testovací pozice - Hledáme pracovnici úklidu</strong>. Nyní systém čeká na souhlas se zpracováním osobních údajů."
                        },
                        {
                            "history_id": 8,
                            "author": "Tereza Barková",
                            "date_time": "11.07.17 14:31",
                            "action_type": "icon-user-following",
                            "action_content": "Personalista manuálně potvrdil schválení osobních údajů pro pozici <strong>Testovací pozice - Hledáme pracovnici úklidu</strong>"
                        },
                        {
                            "history_id": 9,
                            "author": "Tereza Barková",
                            "date_time": "11.07.17 14:39",
                            "action_type": "icon-action-redo",
                            "action_content": "Uchazeč <strong>Will Smith</strong> byl přiřazen k inzerátu <strong>Aha</strong>. Nyní systém čeká na souhlas se zpracováním osobních údajů."
                        },
                        {
                            "history_id": 10,
                            "author": "Tereza Barková",
                            "date_time": "11.07.17 14:39",
                            "action_type": "icon-envelope",
                            "action_content": "Uchazečovi byla odeslána zpráva \"Připomenutí nabídky pracovní pozice\"."
                        },
                        {
                            "history_id": 11,
                            "author": "Tereza Barková",
                            "date_time": "11.07.17 14:41",
                            "action_type": "fa-tags",
                            "action_content": "Uchazeči <strong>Will Smith</strong> byly přidány tyto tagy: <strong>oprávnění C</strong>."
                        }
                    ]
                },
            "meta": 
                {
                    "code": 200,
                    "message": "OK"
                }
        }
        
+ Response 404 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 404,
                    "message": "Candidate with {candidate_id} doesn't exists."
                }
        }
   
 

        
# Group Jobs
API calls for actions connected with jobs.

## Jobs Detail [/jobs/{id}]

+ Parameters
    + id (optional, number, `1`) - Job id

### Get Jobs Detail [GET]

+ Response 200 (application/json)

        {
            "payload":
                [
                    {
                        "job_id": 123456,
                        "title": "Android Developer",
                        "source_site": "PRACEvCR.cz",
                        "personalist": "Tomáš Krátký",
                        "date_created": "23.03.17 17:42",
                        "views": 92,
                        "answers": 8,
                        "active": true,
                        "public_link": "http://ceskytrhprace.pracevcr.cz/detail/347677-mamca-s-dusi-personalistky",
                        "edit_link": "http://pracevcr.cz/zadavatel/inzerat/novy/iid347677/sid07ec2194ec509104427c0a4da7955bc8"
                    }
                ],
            "meta": 
                {
                    "code": 200,
                    "message": "OK"
                }
        }
        
+ Response 404 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 404,
                    "message": "Job with {job_id} doesn't exists."
                }
        }
        

            
## Jobs Lists [/jobs]

### Get All Jobs [GET]

+ Response 200 (application/json)

        {
            "payload": [
                    {
                        "job_id": 123456,
                        "title": "Android Developer",
                        "source_site": "PRACEvCR.cz",
                        "personalist": "Tomáš Krátký",
                        "date_created": "2017-03-23 17:42:10",
                        "views": 92,
                        "flow_answers": [
                            {
                            "flow": 0,
                            "value": 9
                            },
                          {
                            "flow": 1,
                            "value": 1
                        },
                          {
                            "flow": 2,
                            "value": 0
                        },
                          {
                            "flow": 3,
                            "value": 0
                        },
                          {
                            "flow": 4,
                            "value": 1
                        },
                          {
                            "flow": 5,
                            "value": 0
                        },
                          {
                            "flow": 6,
                            "value": 0
                        },
                          {
                            "flow": 7,
                            "value": 0
                        },
                          {
                            "flow": 8,
                            "value": 0
                        },
                          {
                            "flow": 9,
                            "value": 0
                        },
                          {
                            "flow": -1,
                            "value": 0
                        }
                        ],
                        "answers": 8,
                        "active": true,
                        "channels": {
                            "portal": {
                                "date_end": false,
                                "date_from": "2017-06-25 10:20:10",
                                "active": true,
                                "paused": false
                            },
                            "company_page": {
                                "date_end": "2017-06-25 10:20:10",
                                "date_from": false,
                                "paused": true,
                                "active": false
                            },
                            "internal": {
                                "date_end": false,
                                "date_from": false,
                                "active": false,
                                "paused": false
                            }
                        }
                    },
                    {
                        "job_id": 123457,
                        "title": "Senior Java Developer",
                        "source_site": "PRACEvIT.cz",
                        "personalist": "Jiří Tichý",
                        "date_created": "2017-02-14 09:30:22",
                        "views": 25,
                         "flow_answers": [
                            {
                            "flow": 0,
                            "value": 9
                            },
                          {
                            "flow": 1,
                            "value": 1
                        },
                          {
                            "flow": 2,
                            "value": 0
                        },
                          {
                            "flow": 3,
                            "value": 0
                        },
                          {
                            "flow": 4,
                            "value": 1
                        },
                          {
                            "flow": 5,
                            "value": 0
                        },
                          {
                            "flow": 6,
                            "value": 0
                        },
                          {
                            "flow": 7,
                            "value": 0
                        },
                          {
                            "flow": 8,
                            "value": 0
                        },
                          {
                            "flow": 9,
                            "value": 0
                        },
                          {
                            "flow": -1,
                            "value": 0
                        }
                        ],
                        "answers": 4,
                        "active": true,
                        "channels": {
                            "portal": {
                                "date_end": false,
                                "date_from": "2017-06-25 10:20:10",
                                "active": true,
                                "paused": false
                            },
                            "company_page": {
                                "date_end": "2017-06-25 10:20:10",
                                "date_from": false,
                                "paused": true,
                                "active": false
                            },
                            "internal": {
                                "date_end": false,
                                "date_from": false,
                                "active": false,
                                "paused": false
                            }
                        }
                    },
                    {
                        "job_id": 123458,
                        "title": "Vrchní podavač mýdel a holka pro všechno ve státní věznici",
                        "source_site": "PRACEvCR.cz",
                        "personalist": "Jan Andrej Arnošt Dobromír Milič Zátopek",
                        "date_created": "2017-13-32 25:73:33",
                        "views": 4092,
                        "flow_answers": [
                            {
                            "flow": 0,
                            "value": 9
                            },
                          {
                            "flow": 1,
                            "value": 1
                        },
                          {
                            "flow": 2,
                            "value": 0
                        },
                          {
                            "flow": 3,
                            "value": 0
                        },
                          {
                            "flow": 4,
                            "value": 1
                        },
                          {
                            "flow": 5,
                            "value": 0
                        },
                          {
                            "flow": 6,
                            "value": 0
                        },
                          {
                            "flow": 7,
                            "value": 0
                        },
                          {
                            "flow": 8,
                            "value": 0
                        },
                          {
                            "flow": 9,
                            "value": 0
                        },
                          {
                            "flow": -1,
                            "value": 0
                        }
                        ],
                        "answers": 886,
                        "active": true,
                        "channels": {
                            "portal": {
                                "date_end": false,
                                "date_from": "2017-06-25 10:20:10",
                                "active": true,
                                "paused": false
                            },
                            "company_page": {
                                "date_end": "2017-06-25 10:20:10",
                                "date_from": false,
                                "paused": true,
                                "active": false
                            },
                            "internal": {
                                "date_end": false,
                                "date_from": false,
                                "active": false,
                                "paused": false
                            }
                        }
                    }
            ],
            "meta": {
                    "code": 200,
                    "message": "OK"
            }
        }
        

+ Response 404 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 404,
                    "message": "The resource you're looking for doesn't exist."
                }
        }
            
# Group Interviews
API calls for actions connected with interviews.

## Interviews Lists [/interviews]

### Get All Interviews [GET]

+ Response 200 (application/json)

        {
            "payload":
                [
                    {
                        "interview_id": 1,
                        "answer_id": 1
                        "candidate_id": 1,
                        "name": {
                            "first_name": "Michal",
                            "last_name": "Macinka",
                            "initials": "MM"
                        },
                        "title": {
                            "before": null,
                            "after": null
                        },
                        "user_img": "http://lide.uhk.cz/fim/student/macinmi1/avatar_2.jpg",
                        "date_from": "21.02.17 09:30",
                        "date_to": "21.02.17 10:30",
                        "personalist": "Tomáš Krátký"
                    },
                    {
                        "interview_id": 2,
                        "candidate_id": 2,
                        "name": {
                            "first_name": "Věra",
                            "last_name": "Chládková",
                            "initials": "VC"
                        },
                        "title": {
                            "before": "Mgr.",
                            "after": null
                        },
                        "user_img": null,
                        "date_from": "17.01.17 11:20",
                        "date_to": "17.01.17 12:20",
                        "personalist": "Jana Tučná"
                    },
                    {
                        "interview_id": 3,
                        "candidate_id": 3,
                        "name": {
                            "first_name": "Jiří",
                            "last_name": "Modrý",
                            "initials": "JM"
                        },
                        "title": {
                            "before": "Ing.",
                            "after": "Ph.D."
                        },
                        "user_img": null,
                        "date_from": "10.04.17 07:00",
                        "date_to": "10.04.17 9:30",
                        "personalist": "Tomáš Krátký"
                    }
                ],
            "meta": 
                {
                    "code": 200,
                    "message": "OK"
                }
        }
        

+ Response 404 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 404,
                    "message": "The resource you're looking for doesn't exist."
                }
        }
            
# Group Newsfeed

API volání, které vrací všechny informace, které se chronologicky staly v systému, popřípade u konkrétního
uchazeče.

## News Lists [/newsfeed{?limit,page,candidateid}]

### Get All News / News for certain candidate [GET]

+ Parameters
    + limit (optional,numeric,`10`) - pocet entit, ktere se maji zobrazit
    + page (optional,numeric,`1`) - strana s vypisem odpovedi
    + candidateid (optional,numeric,`1`) - Vypíše historii akcí jen ke konkrétnímu uchazeči

+ Response 200 (application/json)

        {
            "payload":
                [ 
                ],
            "meta": 
                {
                    "code": 200,
                    "message": "OK"
                }
        }
        

+ Response 404 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 404,
                    "message": "The resource you're looking for doesn't exist."
                }
        }
            
# Group Miscellaneous

## Send Email Message [/messages/send/email/]

### Send Email [POST]

Procedura na poslání emailu danému uchazeči

+ Request  (application/json)

        {
            "jobid":31116,
            "title":"testovací zpráva",
            "body":"testuji %OSLOVENI%",
            "recipients":"251663,251654,111"
        }

+ Response 201 (application/json)

        {
            "payload": {
                "title": "Zamítnutí uchazeče",
                "body": "Dobrý den, děkujeme Vám za účast ve výběrovém řízení na pozici %INZERAT%, bohužel Vám musíme sdělit, že byl vybrán vhodnější kandidát. Děkujeme za pochopení a přejeme mnoho úspěchů. S pozdravem, %MOJEJMENO% %SPOLECNOST%"
            },
            "meta": {
                "duration": 2259,
                "code": 200,
                "message": "",
                "message_localized": "Přihlášení proběhlo v pořádku"
            }
        }

## Send SMS Message [/messages/send/sms/]

### Send SMS [POST]

Procedura na poslání SMS danému uchazeči. Uchazeč musí mít k sobě přidělen telefonní kontakt. 
Pokud nemá, funkce vrací

+ Request  (application/json)

        {
            "jobid":31116,
            "body":"testuji %OSLOVENI%",
            "recipients":"251663,251654,111"
        }

+ Response 201 (application/json)

        {
            "payload": {
                "body": "Dobrý den, děkujeme Vám za účast ve výběrovém řízení na pozici %INZERAT%, bohužel Vám musíme sdělit, že byl vybrán vhodnější kandidát. Děkujeme za pochopení a přejeme mnoho úspěchů. S pozdravem, %MOJEJMENO% %SPOLECNOST%"
            },
            "meta": {
                "duration": 2259,
                "code": 200,
                "message": "",
                "message_localized": ""
            }
        }

        
## Get Email Template [/email/template/email/{id}]

### Get Email template [GET]

Volání, které vrátí nejvhodnější šablonu emailu. Pokud si daný uživatel vytvořil svojí, vrátí
se mu prioritně ona.

+ Parameters
    + id (numeric,`10`) - ID stavu, pro ktere se ma dana sablona vratit

+ Response 201 (application/json)

        {
            "payload": {
                "title": "Zamítnutí uchazeče",
                "body": "Dobrý den, děkujeme Vám za účast ve výběrovém řízení na pozici %INZERAT%, bohužel Vám musíme sdělit, že byl vybrán vhodnější kandidát. Děkujeme za pochopení a přejeme mnoho úspěchů. S pozdravem, %MOJEJMENO% %SPOLECNOST%"
            },
            "meta": {
                "duration": 2259,
                "code": 200,
                "message": "",
                "message_localized": ""
            }
        }
        
+ Response 404 (application/json)

        {
            "payload": null,
            "meta": {
                "duration": 39,
                "code": 404,
                "message": "",
                "message_localized": ""
            }
        }
        
## Get SMS Template [/messages/template/sms/{id}]

### Get SMS template [GET]

Volání, které vrátí nejvhodnější šablonu pro SMS. Pokud si daný uživatel vytvořil svojí, vrátí
se mu prioritně ona.

+ Parameters
    + id (numeric,`10`) - ID stavu, pro ktere se ma dana sablona vratit

+ Response 201 (application/json)

        {
            "payload": {
                "body": "Dobrý den, děkujeme Vám za účast ve výběrovém řízení na pozici %INZERAT%, bohužel Vám musíme sdělit, že byl vybrán vhodnější kandidát. Děkujeme za pochopení a přejeme mnoho úspěchů. S pozdravem, %MOJEJMENO% %SPOLECNOST%"
            },
            "meta": {
                "duration": 2259,
                "code": 200,
                "message": "",
                "message_localized": ""
            }
        }
        
+ Response 404 (application/json)

        {
            "payload": null,
            "meta": {
                "duration": 39,
                "code": 404,
                "message": "",
                "message_localized": ""
            }
        }
        

## Comments [/comments/{?id,field,argument}]
### get specifics comments [GET]

+ Parameters
    + id (optional, number, `1`)
    ID konkrétního komentáře.
    + field (required, string, `applicant`) 
    Místo, ke kterému se komentáře vztahuje. Nyní jsou povoleny dve hodnoty: `applicant` a `offer`.
    + argument (required, number, `123456`)
    ID daného `fieldu`: Takže buď ID uchazeče, nebo ID inzerátu

+ Response 200 (application/json)

        {
            "payload": [
                {
                    "id": "30138",
                    "body": "gmeaio fjweapi fjweaoif jweaij",
                    "author": "Štěpán Bartyzal",
                    "author_id": "8699",
                    "date_created": "2017-08-28 14:18:24",
                    "date_edited": null,
                    "tags": []
                },
                {
                    "id": "30139",
                    "body": "faiop fjwepoa fjpweoaj fjpweagpjowejgop",
                    "author": "Štěpán Bartyzal",
                    "author_id": "8699",
                    "date_created": "2017-08-28 14:18:26",
                    "date_edited": null,
                    "tags": []
                }
            ],
            "meta": 
                {
                    "code": 200,
                    "message": "OK"
                }
        }
        
+ Response 404 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 404,
                    "message": "Nebyly nalezeny žádné komentáře."
                }
        }
        
## Jobs Detail [/jobs/{id}/customflow]

+ Parameters
    + id (optional, number, `1`) - Job id

### Get Jobs Detail [GET]

+ Response 200 (application/json)

        {
            "payload":
                [
                    {
                        "job_id": 123456,
                        "title": "Testovací inzerát s dynamickým flow",
                        "source_site": "PRACEvCR.cz",
                        "personalist": "Michal Macinka",
                        "date_created": "23.03.17 17:42",
                        "views": 92,
                        "answers": 8,
                        "active": true,
                        "public_link": "http://ceskytrhprace.pracevcr.cz/detail/347677-mamca-s-dusi-personalistky",
                        "edit_link": "http://pracevcr.cz/zadavatel/inzerat/novy/iid347677/sid07ec2194ec509104427c0a4da7955bc8"
                    }
                ],
            "meta": 
                {
                    "code": 200,
                    "message": "OK"
                }
        }
        
+ Response 404 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 404,
                    "message": "Job with {job_id} doesn't exists."
                }
        }
        

            
## Jobs Lists [/jobs/customflow]

### Get All Jobs [GET]

+ Response 200 (application/json)

        {
            "payload": [
                    {
                        "job_id": 123456,
                        "title": "Testovací inzerát s dynamickým flow",
                        "source_site": "PRACEvCR.cz",
                        "personalist": "Michal Macinka",
                        "date_created": "2017-03-23 17:42:10",
                        "views": 92,
                        "flow_answers": [
                            {
                            "action_id": 0, 
                            "flow_id": 40,
                            "label": "nová odpověď",
                            "value": 2
                            },
                          {
                            "action_id": 1, 
                            "flow_id": 43,
                            "label": "nerozřazení",
                            "value": 1
                        },
                          {
                            "action_id": 3, 
                            "flow_id": 45,
                            "label": "telefon",
                            "value": 2
                        },
                          {
                            "action_id": 4, 
                            "flow_id": 47,
                            "label": "1. pohovor",
                            "value": 3
                        },
                          {
                            "action_id": 4, 
                            "flow_id": 48,
                            "label": "2. pohovor",
                            "value": 4
                        },
                          {
                            "action_id": 6, 
                            "flow_id": 49,
                            "label": "přijatí",
                            "value": 4
                        },
                          {
                            "action_id": -1, 
                            "flow_id": 50,
                            "label": "zamítnutí",
                            "value": 3
                        }
                        ],
                        "answers": 8,
                        "active": true,
                        "channels": {
                            "portal": {
                                "date_end": false,
                                "date_from": "2017-06-25 10:20:10",
                                "active": true,
                                "paused": false
                            },
                            "company_page": {
                                "date_end": "2017-06-25 10:20:10",
                                "date_from": false,
                                "paused": true,
                                "active": false
                            },
                            "internal": {
                                "date_end": false,
                                "date_from": false,
                                "active": false,
                                "paused": false
                            }
                        }
                    }
            ],
            "meta": {
                    "code": 200,
                    "message": "OK"
            }
        }
        

+ Response 404 (application/json)

        {
            "payload": null,
            "meta": 
                {
                    "code": 404,
                    "message": "The resource you're looking for doesn't exist."
                }
        }