| Value | Note                              |
|:------|-----------------------------------|
| `1`   | Příloha bez zaměření              |
| `2`   | CV příloha                        |
| `3`   | Emailová korespondence (obsolete) |
| `4`   | Fotografie                        |
| `5`   | GDPR souhlas                      |
