| Value     | Note                                                                                                                    |
|:----------|-------------------------------------------------------------------------------------------------------------------------|
| `tag.hot` | Tento tag přidaný k uchazeči (přes přidání odpovědi / uchazeče) zaručí, že se kandidát zařadí do sekce "žhavý kandidát" |
