# Group Enumerations

Sekce, která má za úkol vracet různé druhy číselníků. Na všechny číselníky se nevztahuje stránkování.


## Workfields Lists [/enums/workfields{?lang}]

Workfields neboli obory a profese používané v Recruitis.io systému.

    
### Get Workfields [GET]

Získá všechny naše profese a obory včetně jejich ID.

#### Requirements

   + No Authorization is needed

+ Parameters
    + lang (optional,string,`cs`) - Jazyk, ve kterém se mají obory vrátit. (momentálně je podporována pouze čeština)
    
+ Response 200 (application/json)

        :[](json/apidoc_enum_workfields.json)
        
        
## Company Workfields Lists [/enums/workfields{?lang,channel_assignation}]


### Get Workfields Used In Jobs [GET]

Získá všechny profese, které jsou obsaženy v inzerátech dané společnosti. Někdy nemusí sedět počet (`count`) oborů při 
součtu `count` podřadných profesí. Je to tím, že mohou mít inzeráty návaznost pouze na obor, nikoliv i na profesi.

*Pro upřesnění: Profese jsou podmnožinou jednotlivých oborů.*

#### Requirements

   + Authorization with token
   + token type: `public_token` : pokud se jedná o dotaz na veřejné inzeráty (vystaveny na firemních stránkách, xml nebo na pracovních portálech)
   + token type: `full_access` : pokud se jedná o dotaz na získání oborů pro interní inzeráty. 
   + Alespoň jeden typ tokenu je tedy vyžadován ve chívli, kdy použijete parametr `channel_assignation`
   
+ Request
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)   

+ Parameters
    + lang (optional,string,`cs`) - Jazyk, ve kterém se mají obory vrátit. (momentálně je podporována pouze čeština)
    + channel_assignation (array[int],``)
    
+ Response 200 (application/json)

        :[](json/apidoc_enum_workfields_company.json)

+ Response 401 (application/json)

        :[](json/apidoc_json_error_401.json)


## Channels List [/enums/channels]

### Get Company Channels [GET]

Získá všechny publikační kanály, na kterých může daná firma publikovat inzeráty. Při filtraci inzerátu lze pak ID kanálu používat jako argument.

#### Requirements

   + Authorization with token
   + token type: `full_access` 
    
+ Response 200 (application/json)

        :[](json/apidoc_enum_channels.json)

+ Response 401 (application/json)

        :[](json/apidoc_json_error_401.json)
        
## Sources List [/enums/sources]

### Get Company Sources [GET]

Vrátí veškeré zdroje a jejich ID. Zdroje mohou být jak definovány samotným systémem, tak i přidány manuálně, firmou.

#### Requirements

   + Authorization with token
   + token type: `public_token` 
    
+ Response 200 (application/json)

        :[](json/apidoc_enum_sources.json)

+ Response 401 (application/json)

        :[](json/apidoc_json_error_401.json)
        
 
## Filter List [/enums/filters]
### Get filters [GET]

**Tato funcionalita ještě není na serveru integrovaná**

Vrací veškeré filtry, které jsou definované pro filtraci inzerátů. 
ID tohoto prvku se následně použije při filtraci inzerátů (volání `jobs` s parametrem `filter_id`)

#### Requirements

   + Authorization with token
   + token type: `public_token`
    
+ Response 200 (application/json)

        :[](json/apidoc_enum_filters.json)

+ Response 401 (application/json)

        :[](json/apidoc_json_error_401.json)


## Filter List [/enums/offices]
### Get filters [GET]

Vrací veškeré pobočky dané společnosti
ID tohoto prvku se následně použije při filtraci inzerátů (volání `jobs` s parametrem `office_id`)

#### Requirements

   + Authorization with token
   + token type: `public_token`
    
+ Response 200 (application/json)

        :[](json/apidoc_enum_offices.json)

+ Response 401 (application/json)

        :[](json/apidoc_json_error_401.json)
