# Group Jobs
API volání, které se vztahuje k aktivním inzerátům.


## Jobs listing [/jobs{?limit,page,workfield_id,office_id,filter_id,channel_id,activity_state,access_state,updated_from,updated_to}]

    
### Get All jobs [GET]

Získání všech inzerátů. Ty se dají filtrovat podle oborů (profesí), filtrů a distribučních kanálů. 

Pokud se nevrátí žádné inzeráty, vrátí se http status `200` s meta code `api.response.null`.

#### Parameters info

 Poznámka: Všechny array parametry udávejte buď jako jednu hodnotu (např. `&office_id=XXX`) nebo 
 jako více hodnot za sebou (např. `&office_id[]=XXX&office_id[]=YYY`).
 
| Parametr                        | Required | Default Value | Require `full_access` token | Note                                                                                                                                                                        |
| :-------------------------------|----------|---------------|-----------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `limit`                         | No       | 10            | No                          | Maximální limit pro stránkovač je 50. Pokud není určen, vrací 10 položek.                                                                                                   |
| `page`                          | No       | 1             | No                          | Aktuální stránka.                                                                                                                                                           |
| `workfield_id`                  | No       |               | No                          | Array. Filtrace podle ID oborů (profesí). Více v číselníku, viz Enumerations.                                                                                               |
| `office_id`                     | No       |               | No                          | Array. Filtrace podle ID poboček.                                                                                                                                           |
| `filter_id`                     | No       |               | No                          | Array. Filtrace podle ID jednotlivých filtračních položek přiřazených k inzerátu. Více v sekci filtračních položek.                                                         |
| `channel_id`                    | No       |               | No                          | Array. Omezení na určité kanály. Více informací o kanálech vrací číselník, viz sekce Enumerations. Pokud není parametr určen, vrátí se všechny možné inzeráty (dle tokenu). |
| `include_inactive` (deprecated) | No       | 0             | Yes                         | Pokud chcete, aby systém vrátil i pozastavené / staré inzeráty, vložte tento parametr s hodnotou 1.                                                                         |
| `only_deleted` (deprecated)     | No       | 0             | Yes                         | Pokud chcete, aby systém vrátil POUZE smazané inzeráty. V tento moment systém vrátí ale payload pouze s job_id parametrem (payload: [{job_id:1234},{job_id:5678}]).         |
| `status` (deprecated)           | No       | 1             | Yes                         | Parametr se chová jako bitmapa. 1 = aktivní, 2 = neaktivní, 4 = draft, 8 = smazaný. Jsou povolené kombinace všech, krom smazaných, které jdou zobrazit pouze samostatně.    |
|                                 |          |               |                             | Status nahrazuje předchozí dva parametry (include_inactive a only_deleted), které jsou deprecated, a při jeho použití jsou ignorovány.                                      |
| `activity_state`                | No       | 1             | Yes                         | Viz. popis atributu níže.                                                                                                                                                   |
| `access_state`                  | No       |               | Yes                         | Viz. popis atributu níže.                                                                                                                                                   |
| `updated_from`                  | No       |               | No                          | Datetime, fitrace podle data poslední editace inzerátu                                                                                                                      |
| `updated_to`                    | No       |               | No                          | Datetime, fitrace podle data poslední editace inzerátu                                                                                                                      |


Tip: Pokud chcete filtrovat podle adres, můžete inzeráty v Recruitisu přiřadit ke konkrétním pobočkám a pak filtrovat podle nich (u poboček vracíme adresy, pod jednou adresou můžete uvést i více poboček).


#### Parametr activity_state

Parametr filtruje pozice podle toho, jestli jsou aktivní nebo neaktivní. Zároveň je parametr bitmapa, tudíž lze jednotlivé hodnoty sčítat a ty používat (Umožňuje filtrovat více možností na jednou.).

| Parameter        | Value | Note                                                          |
|------------------|-------|---------------------------------------------------------------|
| Aktivní pozice   | 1     | Pozice, která se nachází alespoň v jednom publikačním kanále. |
| Neaktivní pozice | 2     | Pozice, která se nenchází v žádném publikačním kanále.        |


#### Parametr access_state

Parametr filtruje inzeráty podle logiky otevřených a uzavřených pozic. Na rozdíl od activity_state **nelze** jednotlivé hodnoty kombinovat.

| Parameter          | Value | Note                                                                                                                                                                                                                                                |
|--------------------|-------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Otevřená pozice    | 1     | Otevřená pozice se nachází alespoň v jednom publikačním kanálu. Lze do ní přidávat odpovědi a jako jediná nepotřebuje `full_access` token.                                                                                                          |
| Uzavřená pozice    | 2     | Uzavřená pozice se nenachází v žádném publikačním kanálu a lze do ní přidávat odpovědi.                                                                                                                                                             |
| Archivovaná pozice | 3     | Archivovaná pozice (dříve smazaná) je pozice určená ke znovu otevření, popř. úplnému smazání. Nepřijímá nové odpovědi a neumožňuje editaci svávajících. Při Archivaci dochází k odosobnění uchazečů bez GDPR souhlasu. Vrací pouze seznam ID pozic. |
| Draft              | 4     | Rozepsaná pozice právě přihlášeného personalisty.                                                                                                                                                                                                   |
| Šablona            | 5     | Pozice určená jako šablona. Může být buď právě přihlášeného personalisty nebo celé firmy.                                                                                                                                                           |


#### Requirements

* Volání musí být s autorizačním tokenem.
* Token typ: `public_access`: pokud se jedná o veřejný inzerát (vystavený na firemních stránkách, xml nebo na pracovních portálech) - (určení dle channel_id).  
* Token typ: `full_access`: pokud se jedná o interní inzerát. (určení dle channel_id). 
* Kompatibilní s firemním tokenem.

+ Request
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)

+ Parameters
    + limit (optional,numeric,`10`) - Počet entit, které se mohou zobrazit.
    + page (optional,numeric,`1`) - Strana s výpisem inzerátů.
    + workfield_id (optional,array[int]) - Omezení na určité pracovní obory, profese.
    + office_id (optional,array[int]) - Omezení na určité pobočky, viz sekce Enumerations.
    + filter_id (optional,array[int]) - Omezení na určité filtry, viz sekce Job Filters.
    + channel_id (optional,array[int]) - Omezení na určité kanály, viz sekce Enumerations.
    + activity_state (optional,numeric) - Omezení na aktivní / neaktivní inzeráty.
    + access_state (optional,numeric) - Omezení na otevřené / uzavřené a archivované inzeráty.
    + updated_from (optional,numeric)  - Omezení na inzeráty s poslední úpravou.
    + updated_to (optional,datetime) - Omezení na inzeráty s poslední úpravou.
    
+ Response 200 (application/json)

        :[](json/apidoc_jobs_list_get.json)

## Job detail [/jobs/{id}?{activity_state,access_state}]

### Get Job detail [GET]

 Vrátí detail jednoho inzerátu. Parametry v odpovědi jsou stejné, jako když se vrací více inzerátů najednou. Je nutné počítat s tím, že se jednotlivé
 argumenty mohou vrátit i jako null namísto stringu, objektu.
 
 **POZOR: 18.9.2018 dojde ke změně odpovědi API volání: Inzerát se nebude vracet v payload jako pole (tzn.: nebude `payload: [{...}]`),
 ale bude se vracet přímo daná odpověď (tzn.: `payload: {...}`).**
 
 Pokud daný inzerát neexistuje, vrátí se http status `404` s meta code `api.error.not_found`.


#### Requirements

* Volání musí být s autorizačním tokenem.
* Kompatibilní s firemním tokenem.
* Token typ: `public_access`: pokud se jedná o veřejný inzerát (vystavený na firemních stránkách, xml nebo na pracovních portálech).
* Token typ: `full_access`: pokud se jedná o interní inzerát.

#### Response parameters

| Parameter                           | token condition   | Type               | Note                                                                                                                                               |
| ----------------------------------  | ----------------- | ---------------    | -------------------------------------------------------------------------------------------------------------------------------------------------- |
| `job_id`                            | `public_access`   | int                | ID inzerátu.                                                                                                                                       |
| `public_id`                         | `public_access`   | string             | Interní označení inzerátu. Nemusí být vyplněné.                                                                                                    |
| `access_state`                      | `public_access`   | int                | Značení o jaký typ pozice se jedná. Viz. access_state parametr.                                                                                    |
| `draft`                             | `public_access`   | bool               | Značí, jestli je inzerát zveřejněný, nebo jen rozepsaný.                                                                                           |
| `active`                            | `public_access`   | bool               | Viz popisek níže.                                                                                                                                  |
| `title`                             | `public_access`   | string             |                                                                                                                                                    |
| `description`                       | `public_access`   | string             |                                                                                                                                                    |
| `date_closed`                       | `public_access`   | date,null          | Dřívější `date_end` signalizující datum, kdy byla pozice naposledy zavřena.                                                                        |
| `closed_duration`                   | `public_access`   | timestamp (int)    | Čas, kdy byl inzerát ve stavu zavřený. Tato hodnota je kumulativní a sčítá veškerý čas i přes několikanásobné zavření a otevření pozice.           |
| `last_update`                       | `public_access`   | datetime           | Datum, kdy byl inzerát naposledy upraven.                                                                                                          |
| `date_created`                      | `public_access`   | datetime           |                                                                                                                                                    |
| `workfields`                        | `public_access`   | array(object)      |                                                                                                                                                    |
| `workfields` - `id`                 | `public_access`   | int                |                                                                                                                                                    |
| `workfields` - `name`               | `public_access`   | string             |                                                                                                                                                    |
| `education`                         | `public_access`   | array(object)      |                                                                                                                                                    |
| `education`  - `id`                 | `public_access`   | int                |                                                                                                                                                    |
| `education` - `name`                | `public_access`   | string             |                                                                                                                                                    |
| `salary`                            | `public_access`   | array(object),null |                                                                                                                                                    |
| `salary` - `min`                    | `public_access`   | double             | Platové ohodnocení - minimální částka                                                                                                              |
| `salary` - `max`                    | `public_access`   | double             | Platové ohodnocení - maximální částka (Pokuď není určeno rozpětí, je uvedena pouze tato hodnota.                                                   |
| `salary` - `currency`               | `public_access`   | string             | Měna ("CZK","EUR","USD")                                                                                                                           |
| `salary` - `unit`                   | `public_access`   | string             | Typ platu ("month","hour","manday")                                                                                                                |
| `salary` - `visible`                | `public_access`   | bool               | Určuje, jestli je tato informace veřejná.                                                                                                          |
| `employment`                        | `public_access`   | array(object)      | Typ pracovního úvazku                                                                                                                              |
| `employment`  - `id`                | `public_access`   | int                |                                                                                                                                                    |
| `employment` - `name`               | `public_access`   | string             |                                                                                                                                                    |
| `stats`                             | `full_access`     | object             | Statistiky k danému inzerátu. Ukazují počty.                                                                                                       |
| `stats` - `flow_answers`            | `full_access`     | array(object)      | Pole jednotlivých stavů a jejich počtu odpovědí.                                                                                                   |
| `stats` - `answers`                 | `full_access`     | int                |                                                                                                                                                    |
| `stats` - `views`                   | `full_access`     | int                |                                                                                                                                                    |
| `fte`                               | `full_access`     | object,null        | FTE (full time equivalent)                                                                                                                         |
| `fte` - `value`                     | `full_access`     | double             | hodnota FTE                                                                                                                                        |
| `fte` - `active`                    | `full_access`     | bool               | Označuje, jestli je FTE aktivní, či nikoli (řeší se u kontinuálního náboru, jinak je vždy true)                                                    |
| `filterlist`                        | `public_access`   | array(object)      | Seznam filtračních položek.                                                                                                                        |
| `filterlist` - `id`                 | `public_access`   | int                |                                                                                                                                                    |
| `filterlist` - `name`               | `public_access`   | string             |                                                                                                                                                    |
| `filterlist` - `group`              | `public_access`   | string             |                                                                                                                                                    |
| `details`                           | `public_access`   | object             |                                                                                                                                                    |
| `details` - `office_id`             | `public_access`   | int,null           | Pokud je inzerát propojený s pobočkou, tato položka obsahuje ID pobočky (podle ní se dá filtrovat). Pokud není propojená, položka se nezobrazuje.  |
| `details` - `facebook_picture_path` | `public_access`   | string,null        | Odkaz na obrázek vhodný jako "og:image" parametr.                                                                                                  |
| `details` - `opening_reson`         | `public_access`   | string,null        | Textový důvod říkající, proč byl inzerát vytvořen.                                                                                                 |
| `personalist`                       | `public_access`   | object             |                                                                                                                                                    |
| `personalist` - `id`                | `public_access`   | int                |                                                                                                                                                    |
| `personalist` - `name`              | `public_access`   | string             |                                                                                                                                                    |
| `contact` - `name`                  | `public_access`   | string             |                                                                                                                                                    |
| `contact` - `email`                 | `public_access`   | string             |                                                                                                                                                    |
| `contact` - `phone`                 | `public_access`   | string             |                                                                                                                                                    |
| `addresses`                         | `public_access`   | array(object)      |                                                                                                                                                    |
| `addresses` - `id`                  | `public_access`   | int                |                                                                                                                                                    |
| `addresses` - `office_id`           | `public_access`   | int                | návaznost na office, viz dotaz `GET enums/offices`                                                                                                 |
| `addresses` - `city`                | `public_access`   | string             |                                                                                                                                                    |
| `addresses` - `psc`                 | `public_access`   | string             |                                                                                                                                                    |
| `addresses` - `street`              | `public_access`   | string             |                                                                                                                                                    |
| `addresses` - `region`              | `public_access`   | string             |                                                                                                                                                    |
| `addresses` - `state`               | `public_access`   | string             |                                                                                                                                                    |
| `draft`                             | `public_access`   | bool               | Značí, jestli je Inzerát draft.                                                                                                                    |

#### Atribut active

Atribut `active` ve výpisu inzerátů značí, jestli je daný inzerát aktivní, to jest, že je právě v tuto chvíli někde publikován a zároveň není pozastaven.  

  * V případě, že je určen filtrační parametr `channel_id`, pak atribut `active` říká, jestli je inzerát aktivní v daném publikačním kanálu.
  * Pokud je ve filtračním parametru `channel_id` více kanálů, pak je atribut `active` = true ve chvíli, kdy je alespoň v jednom z daných publikačních kanálů aktivní.
  * Pokud filtrační parametr `channel_id` *není* určen, poté atribut `active` říká, jestli je inzerát aktivní alespoň v jednom ze všech publikáčních kanálů (tzn: je *kdekoli* právě vystaven.).

+ Request
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)

+ Parameters
    + id (number, `1`) - Job id
    + activity_state (optional,numeric) - Omezení na aktivní / neaktivní inzeráty.
    + access_state (optional,numeric) - Omezení na otevřené / uzavřené a archivované inzeráty.



+ Response 200 (application/json)

        :[](json/apidoc_jobs_detail_get.json)

        
+ Response 401 (application/json)

        :[](json/apidoc_json_error_401.json)

## Job creation [/jobs]

### Create new job [POST]

Procedura vytvoří nový inzerát a dá ho do rozepsaných. Následně je možné inzerát dokončit přímo v systému Recruitis. Při správném vytvoření se vrátí i odkaz na jeho dokončení.

#### Důležitá informace:
**Při testování POST požadavku v Apiary.io na produkčním serveru: Základní token míří na testovací účet, ke kterému mají přístup i ostatní uživatelé. 
Neposílejte tedy své osobní údaje přes tento token, popřípadě si token změňte na svůj vlastní.**

#### Requirements

* Volání musí být s autorizačním tokenem.
* Token typ: `full_access`: pro vytvoření inzerátu potřebujeme vždy full access.
   
| Request value                          | Required   | Default Value     | Note                                                                                                                                                                                                                           |
| :------------------------------------- | ---------- | :---------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| `title`                                | Yes        |                   | Název pozice.                                                                                                                                                                                                                  |
| `description`                          | Yes        |                   | Popis pozice.                                                                                                                                                                                                                  |
| `text_language`                        | No         | cs                | Určuje, v jakém jazyce je psaný popisek pozice. Povolené hodnoty jsou cs,sk,en,de.                                                                                                                                             |
| `author_id`                            | No         |                   | ID zaměstnance, pod kterým se inzerát založí (pokud není vyplněno, využije se ten, pod kterým je přihlášeno API).                                                                                                              |


+ Request (application/json)
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)

    + Body  

            :[](json/apidoc_jobs_post_request.json)

+ Response 201 (application/json)

        :[](json/apidoc_json_post_general.json MSG:"Job was created." CODE:"api.created")
        
+ Response 400 (application/json)
        
        :[](json/apidoc_json_error_general.json MSG:"Can't create job" CODE:"api.error.generic")
        
        
## Job channels list [/jobs/{id}/channels]

### Show list of channels [GET]

Zobrazení všech kanálů, kde je inzerát publikován.

#### Requirements

* Volání musí být s autorizačním tokenem.
* Token typ: `full_access`: pro publikaci inzerátu je potřeba full access
   
+ Request (application/json)
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)

+ Response 200 (application/json)

    # todo
        :[](json/apidoc_jobs_channels_get_response.json MSG:"Job channels found." CODE:"api.found")
              
+ Response 404 (application/json)
        
        :[](json/apidoc_json_error_404.json)
         
## Publishing on channel [/jobs/{id}/channel/{channel_id}]

### Publish job [PUT]

Vystavení aktivního inzerátu na nějakém z prezentačních kanálů. V případě, že je inzerát na daném kanálu již vystaven, bude nastavení aktualizováno.


#### Requirements

* Volání musí být s autorizačním tokenem.
* Token typ: `full_access`: pro publikaci inzerátu je potřeba full access

| Request value                          | Required   | Type        | Default Value     | Note                                                                                                                  |
| :------------------------------------- | ---------- | :---------- | ----------------- | --------------------------------------------------------------------------------------------------------------------- |
| `date_from`                            | Yes        | datetime    |                   | Datum, od kdy má být inzerát na daném kanále vystaven. Pokud není vyplněno, použije se aktuální datum a čas.          |
| `date_to`                              | Yes        | datetime    |                   | Datum, do kdy má být inzerát na daném kanále vystaven.                                                                |


+ Request (application/json)
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)

    + Body  

            :[](json/apidoc_jobs_channel_put_request.json)

+ Parameters
    + id (numeric,`123456`) - Id inzerátu.
    + channel_id (optional,numeric,`1`) - Id publikačního kanálu.
        
+ Response 200 (application/json)

        :[](json/apidoc_jobs_channel_put_response.json)
        
+ Response 400 (application/json)
        
        :[](json/apidoc_json_error_general.json MSG:"Draft cannot be published" CODE:"api.error.generic")
        
+ Response 404 (application/json)
        
        :[](json/apidoc_json_error_404.json)
        

## Job access state operation [/jobs/{id}/access_state/{state}]

### Changing job access state [PUT]

Změna přístupu k pozici. Jedná se o uzavírání, otevírání a archivaci pozic. Více je popsáno v sekci [parameter-access_state](#parameter-access_state).


#### Requirements

* Volání musí být s autorizačním tokenem.
* Token typ: `full_access`: pro publikaci inzerátu je potřeba full access

  + Request (application/json)
      + Headers
    
              Authorization: Bearer :[](apidoc_bearer_token.txt)
            

+ Parameters
    + id (numeric,`123456`) - Id inzerátu.
    + state (optional,numeric,`1`) - Id parametru access_state. (viz. dokumentace přímo tohoto parametru.)
        
+ Response 200 (application/json)

        :[](json/apidoc_jobs_access_state_put_response.json)

        
+ Response 404 (application/json)
        
        :[](json/apidoc_json_error_404.json)
        
        
### Unpublish job [DELETE]

Stažení inzerátu z prezentačního kanálu.

#### Requirements

* Volání musí být s autorizačním tokenem.
* Token typ: `full_access`: pro publikaci inzerátu je potřeba full access
   
+ Request (application/json)
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)

+ Response 202 (application/json)

        :[](json/apidoc_jobs_channel_delete_response.json)
        
+ Response 400 (application/json)
        
        :[](json/apidoc_json_error_general.json MSG:"Draft cannot be unpublished" CODE:"api.error.generic")
        
+ Response 404 (application/json)
        
        :[](json/apidoc_json_error_404.json)


## Communication with candidate [/jobs/{id}/communication{?limit,page,candidate_id,direction,type}]      
        
### List communication with candidates [GET]

Výpis komunikace s kandidáty na konkrétní pozici.

+ Request (application/json)
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)
            
+ Response 200 (application/json)

        :[](json/apidoc_jobs_communication_get.json)
