FORMAT: 1A
HOST: http://polls.apiblueprint.org/

FORMAT: 1A
HOST: https://pracevcr.cz/api2/

# Recruitis.io
API dokumentace pro systém Recruitis.io (http://recruitis.io).
Dokumentace je založena na autorizace pomocí tokenu, která je vyhgenerován buď samotným systémem. nebo uživatelem.
Token se posílá v Header položce "Authorization: bearer XXX"

Postupem řasu budou příbývat jednotlivé funkcionality. Pokud by měla být narušena funčnost jakéhokoli API volání, 
bude založen nový branch (v2 atd.), nebo budete dostatečným časovým rozestupem o změně informováni.

#### Tokeny
Autorizační tokeny mají dvě úrovně:
+ `full_access` : Token, který má veškeré pravomoce a umožňuje upravovat data v systému dané firmy.
Tento token nesmí být jakkoli zobrazen veřejnosti.
+ `public_access` : Token, který má převážně zobrazovací pravomoce. Tento token může být veřejnosti zobrazen. Například při použití Javascriptu.

Na oba druhy tokenů lze uplatnit doménový whitelist. (Toto nastavení doporučujeme použít.)
Tokeny lze vytvořit v Recrutis > *nastavení* > *api propojení*.  


:[group_login](apidoc_group_login.apib)

:[group_me](apidoc_group_me.apib)

:[group_jobs](apidoc_group_jobs.apib)

:[group_answers](apidoc_group_answers.apib)

#CHANGELOG
:[changelog](apidoc_changelog.apib)