# Group Files
Tato sekce umožňuje správu souborů, momentálně jejich stahování.


## File Lists [/files/{?hash}]

    
### Download a file [GET]

Stahování souboru probíhá tak, že Vám API vrátí payload s base64 stringem, který si následně můžete překonvertovat do daného souboru.
Daný hash nyní vrací funkce [`GET`] `answers/`, který vrací celou url adresu i s daným hashem (např.: "https://api.recruitis.io/api2/files/YXdQMmRtWWprNXBTY042M1hFOTdvZz09")


Pokud soubor neexistuje, nebo nepatří Vaší firmě, vrací se http status `404` s meta code `api.error.not_found`.

#### Requirements

* Volání musí být s autorizačním tokenem.
* Nový typ tokenů:
  * Token musí mít oprávnění `api.files.read`.
* Starý typ tokenů:
  * Token typ: `full_access`

#### Parameters info

| Parametr | Required | Default Value | Require `full_access` token | Note                                                                                   |
|----------|----------|---------------|-----------------------------|----------------------------------------------------------------------------------------|
| `hash`   | Yes      |               | Yes                         | string,array. Hash je rozpoznávací string, díky kterému systém ví, jaký soubor vrátit. |

Parametr `hash` lze použít i jako pole (`?hash[]=xxxxx&hash[]=yyyyyy`). V tom případě se i **payload vrací jako pole**.


#### Response parameters

| Parametr  | token condition | Type   | Note                                                                      |
|-----------|-----------------|--------|---------------------------------------------------------------------------|
| `name`    | `full_access`   | string | Název souboru i příponou.                                                 |
| `size`    | `full_access`   | double | Velikost souboru v KB (dvě desetinná místa).                              |
| `content` | `full_access`   | string | Znění souboru v Base64.                                                   |
| `hash`    | `full_access`   | string | Vrací se na zpět pouze v případě, že je parametr `hash` použit jako pole. |

** V případě dotázání více příloh, je potřeba, aby součet velikostí všech příloh byl menší než 30MB. Pokud je součet
příloh větší, API vrátí http stav `413` s meta kódem `api.error.response.too_big`**


+ Request
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)

+ Parameters
    + hash (string,`cFMrMmRoWGpNVVNLbDlHM2lweWJ6UT09`) - Identifikátor souboru.
    
+ Response 200 (application/json) 

        :[](json/apidoc_files_get.json)
        
+ Response 404 (application/json)

        :[](json/apidoc_json_error_404.json)
        
+ Response 413 (application/json)

        :[](json/apidoc_json_error_413.json)
