#Group Me

## My account information [/me]

### Me [GET]

Získání informací o právě přihlášeném účtu.

#### Requirements

* Volání musí být s autorizačním tokenem.
* Kompatibilní s firemním tokenem.

+ Request
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)

+ Response 200 (application/json)

        :[](json/apidoc_me.json)


+ Response 401 (application/json)

        :[](json/apidoc_json_error_401.json)