#Group Me

## My account information [/me]

### Me [GET]

#### Requirements

* Volání musí být s autorizačním tokenem.
* Kompatibilní s firemním tokenem.
* Token typ: `public_access` a `full_access`

#### Zobrazení parametru závislém na druhu tokenu

| Parametr | token         | Poznámka |
|:---------|---------------|----------|
| `stats`  | `full_access` |          |

####Vysvětlení flow hodnot

| Flow ID | Vysvětlení          | Poznámka                                             |
|:--------|---------------------|------------------------------------------------------|
| `0`     | Status "Nový        |                                                      |
| `1`     | Status "Nepřiřazený |                                                      |
| `2`     | Status "Další kolo  | Toto ID se momentálně nepoužívá.                     |
| `3`     | Status "Telefon     |                                                      |
| `4`     | Status "Pohovor     |                                                      |
| `5`     | Status "Vybrán      |                                                      |
| `6`     | Status "Přijat      |                                                      |
| `8`     | Status "Smazán      | Toto ID zapříčiní, že daný uchazeč z odpovědi zmizí. |

Získání informací o mém účtu, za kterého jsem právě přihlášen.

+ Request
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)
            
+ Parameters
    + limit (optional,numeric,`10`) - počet entit, které se mají zobrazit.
    + page (optional,numeric,`1`) - strana s výpisem odpovědí.
    + search (optional,string) - Vyhledávání ve jméně.
    + jobid (optional,int) - Omezení na určitý inzerát.
    + status (array[int])

+ Response 200 (application/json)

        :[](json/apidoc_json_template.json)

+ Response 404 (application/json)

        :[](json/apidoc_json_error_general.json MSG:"Inzerát nebyl nalezen" CODE:"api.error.jobs.notfound.one")

+ Response 401 (application/json)

        :[](json/apidoc_json_error_401.json)


### Me [POST]

Procedura na uložení nového "me"

+ Request  (application/json)

        {
            "name": "Pavel,
            "surname":  "Test",
            "email":    "aaa@test.cz",
            "pole": "1,43,45,933",
        }

+ Response 201 (application/json)

        {
            "payload": {
                id: 1
            },
            "meta": {
                "duration": 2259,
                "code": api.created,
                "message_localized": "Byl jsem úspěšně vložen"
            }
        }
        
### Me [PUT]

Procedura na upravení nového "me".

+ Request  (application/json)

        {
            "name": "Pavlásek",
            "id": 1,
        }

+ Response 200 (application/json)

        {
            "payload": {
                id: 1
            },
            "meta": {
                "duration": 2259,
                "code": api.updated,
                "message_localized": "Byl jsem úspěšně upraven"
            }
        }