# Group Enumerations

Sekce, která má za úkol vracet různé druhy číselníků. Na všechny číselníky se nevztahuje stránkování.

#### suitable_for parameter

Tento parametr posíláme v detailech jednotlivých inzerátů. Pokud není parametr určen, v payloadu se nenachází.

| ID  | Hodnota                    |
|-----|----------------------------|
| 1   | Absolvent                  |
| 2   | Důchodce                   |
| 3   | Na rodičovské dovolené     |
| 4   | Nezaměstnaný               |
| 5   | vojenské služby: NVS, ZVS  |
| 6   | OSVČ                       |
| 7   | Student                    |
| 8   | Zaměstnaný                 |
| 10  | Není vhodná pro absolventy |

#### remote_work parameter

Tento parametr posíláme v detailech jednotlivých inzerátů. Pokud není parametr určen, v payloadu se nenachází.

| Hodnota | Popis                        |
|---------|------------------------------|
| full    | Povolená 100% práce z domova |
| partial | Částečná práce z domova      |


## Workfields Lists [/enums/workfields{?lang}]

Workfields neboli obory a profese používané v Recruitis.io systému.

    
### Get Workfields [GET]

Získá všechny naše profese a obory včetně jejich ID.

#### Requirements

   + Není potřeba žádná autorizace.

+ Parameters
    + lang (optional,string,`cs`) - Jazyk, ve kterém se mají obory vrátit (momentálně je podporována pouze čeština).
    
+ Response 200 (application/json)

        :[](json/apidoc_enum_workfields.json)
        
        
## Company Workfields Lists [/enums/workfields{?lang,channel_assignation}]


### Get Workfields Used In Jobs [GET]

Získá všechny profese, které jsou obsaženy v inzerátech dané společnosti. Někdy nemusí sedět počet (`count`) oborů při 
součtu `count` podřadných profesí. Je to tím, že mohou mít inzeráty návaznost pouze na obor, nikoliv i na profesi.

*Pro upřesnění: Profese jsou podmnožinou jednotlivých oborů.*

#### Requirements

* Volání musí být s autorizačním tokenem.
* Kompatibilní s firemním tokenem.
* Nový typ tokenů:
  * Token musí mít oprávnění `api.enums.read`.
* Starý typ tokenů:
  * Token typ: `public_access`, `full_access`   


+ Request
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)   

+ Parameters
    + lang (optional,string,`cs`) - Jazyk, ve kterém se mají obory vrátit (momentálně je podporována pouze čeština).
    + channel_assignation (array[int],``)
    
+ Response 200 (application/json)

        :[](json/apidoc_enum_workfields_company.json)

+ Response 401 (application/json)

        :[](json/apidoc_json_error_401.json)


## Channels List [/enums/channels]

### Get Company Channels [GET]

Získá všechny publikační kanály, na kterých může daná firma publikovat inzeráty. Při filtraci inzerátu lze pak ID kanálu používat jako argument.

#### Requirements

* Volání musí být s autorizačním tokenem.
* Kompatibilní s firemním tokenem.
* Nový typ tokenů:
  * Token musí mít oprávnění `api.enums.read`.
* Starý typ tokenů:
  * Token typ: `public_access`, `full_access`

+ Response 200 (application/json)

        :[](json/apidoc_enum_channels.json)

+ Response 401 (application/json)

        :[](json/apidoc_json_error_401.json)
        
## Sources List [/enums/sources]

### Get Company Sources [GET]

Vrátí veškeré zdroje a jejich ID. Zdroje mohou být definovány jak samotným systémem, tak i přidány manuálně, firmou.

#### Requirements

* Volání musí být s autorizačním tokenem.
* Kompatibilní s firemním tokenem.
* Nový typ tokenů:
  * Token musí mít oprávnění `api.enums.read`.
* Starý typ tokenů:
  * Token typ: `public_access`, `full_access`

+ Response 200 (application/json)

        :[](json/apidoc_enum_sources.json)

+ Response 401 (application/json)

        :[](json/apidoc_json_error_401.json)
        
 
## Office List [/enums/offices]
### Get offices [GET]

Vrací veškeré pobočky dané společnosti,
ID tohoto prvku se následně použije při filtraci inzerátů (volání `jobs` s parametrem `office_id`).

#### Requirements

* Volání musí být s autorizačním tokenem.
* Kompatibilní s firemním tokenem.
* Nový typ tokenů:
  * Token musí mít oprávnění `api.enums.read`.
* Starý typ tokenů:
  * Token typ: `public_access`, `full_access`

+ Response 200 (application/json)

        :[](json/apidoc_enum_offices.json)

+ Response 401 (application/json)

        :[](json/apidoc_json_error_401.json)



## Employment List [/enums/employments{?lang}]
### Get offices [GET]

Vrací všechny naše pracovní poměry a jejich ID.

#### Requirements

   + Není potřeba žádná autorizace.
   
+ Parameters
   + lang (optional,string,`cs`) - Jazyk, ve kterém se mají obory vrátit (momentálně je podporována pouze čeština).
       
+ Response 200 (application/json)

       :[](json/apidoc_enum_employments.json)
