# Group Referrals

Tato sekce se vztahuje k referralům systému Recruitis. Tyto referralové mají přístup do své sekce, odkud mohou sdílet nasdílené inzeráty a tím
hledat nové zaměstnance skrze vypsané odměny. 

## Referral entity [/referrals{?id,limit,page,search}]

### Create new referral [POST]
Procedura na uložení nového referrala. Jako odpověď se vrátí ID referrala. 
V případě, že daný referral již existuje, server vrací header status `409`.

#### Důležitá informace:
**Při testování POST požadavku v Apiary.io na produkčním serveru: Základní token míří na testovací účet, ke kterému mají přístup i ostatní uživatelé. 
Neposílejte tedy své osobní údaje přes tento token, popřípadě si token změňte na svůj vlastní.**

#### Requirements

* Volání musí být s autorizačním tokenem.
* Kompatibilní s firemním tokenem.
* Nový typ tokenů:
  * Token musí mít oprávnění `api.referral.write`.
* Starý typ tokenů:
  * Token typ: `full_access`
   
 | Request value | Required | Note                                                                                                                                      |
|:--------------|----------|:------------------------------------------------------------------------------------------------------------------------------------------|
 | `name`        | Yes      | Jméno referrala.                                                                                                                          |
 | `email`       | No       | Email referrala.                                                                                                                          |
 | `phone`       | No       | Telefon referrala.                                                                                                                        |
 | `email_text`  | No       | Pokud je zadáno, pak se tento email rovnou při vytvoření referrala pošle na určený email. Podporuje i proměnné, viz šablony v Recruitisu. |

+ Request (application/json)
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)

    + Body
        
            :[](json/apidoc_referrals_post_request.json)

+ Response 201 (application/json)

        :[](json/apidoc_referrals_post_response.json)

        
+ Response 409 (application/json)

        :[](json/apidoc_json_post_general.json MSG:"This referral already exists." CODE:"api.error.referral.already_created")
        
### Get referral list [GET]

Zavolání vrátí veškeré referraly přidružené k dané firmě. Na výpis se vztahuje stránkovač, kde maximum entit na jednu stránku je 100.
V případě, že neodpovídá filtru žádný referral (nebo firma žádného referrala nemá), systém vrací header status `200` s `meta.code` `api.response.null`.

#### Requirements

* Volání musí být s autorizačním tokenem.
* Nový typ tokenů:
    * Token musí mít oprávnění `api.referral.read`.
* Starý typ tokenů:
    * Token typ: `full_access`

#### Response parameters

| Parameter      | Type     | Note                                                                               |
|----------------|----------|------------------------------------------------------------------------------------|
| `id`           | string   | ID referrala.                                                                      |
| `access_id`    | string   | Veřejné ID referrala, přes který má přístup ke svému portálu, viz  `url` parametr. |
| `name`         | string   | Jméno referrala.                                                                   |
| `photo`        | date     | Pokud je zadáno, tak je zde odkaz na fotku referrala.                              |
| `date_created` | datetime | Datum vzniku referrala.                                                            |
| `date_visited` | datetime | Datum, kdy naposledy referral navštívil svojí stránku.                             |
| `email`        | string   | Email referrala.                                                                   |
| `url`          | string   | Odkaz na adresu stránky referrrala.                                                |
                            
                            
+ Parameters
     + id (optional, string, `xseo35fe`) - ID referrala, popř. access_id referrala. ID se může zadat i jako array. Pozor: nekombinujte referral ID a referral access_id.
     + limit (optional,numeric,`10`) - maximální počet entit, které má server vrátit. Maximální limit je 100.
     + page (optional,numeric,`1`) - strana s entitami.
     + search (optional,string) - Vrátí referraly s daným jménem, popř. emailem.
    
+ Request
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)
                
+ Response 200 (application/json)

                :[](json/apidoc_referrals_get_response.json)
                
                
### Get referral [GET /referrals/{id}]

Vrátí konkrétního referrala. Pokud je zadáno jedno ID a není zadáno jako pole v GET parametrech, poté se vrátí jako jedna entita, tzn. payload nebude obsahovat pole.
V případě, že daný referral neexistuje, vrací se `404` odpověď. 

#### Requirements

* Volání musí být s autorizačním tokenem.
* Nový typ tokenů:
    * Token musí mít oprávnění `api.referral.read`.
* Starý typ tokenů:
    * Token typ: `full_access`

+ Parameters
     + id (required, string, `xseo35fe`) - ID referrala, popř. access_id referrala.
     
+ Request
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)

+ Response 200 (application/json)

        :[](json/apidoc_referrals_get_one_response.json)

+ Response 404 (application/json)
        
        :[](json/apidoc_json_error_general.json MSG:"Referral ID XXX doesn't exists." CODE:"api.error.not_found")