# Group Jobs
API volání, které se vztahuje k aktivním inzerátům.


## Job Lists [/jobs{?limit,page,workfield_id,office_id,filter_id,channel_id,include_inactive,only_deleted}]

    
### Get All Jobs [GET]

Získání všech inzerátů. Ty se dají filtrovat podle oborů (profesí), filtrů a distribučních kanálů. 

Pokud se nevrátí žádné inzeráty, vrátí se http status `200` s meta code `api.response.null`.

#### Parameters info

 Poznámka: Všechny array parametry udávejte buď jako jednu hodnotu (např. `&office_id=XXX`) nebo 
 jako více hodnot za sebou (např. `&office_id[]=XXX&office_id[]=YYY`).
 
| Parameter          | Required | Default Value | Require `full_access` token | Note                                                                                                                                                                        |
|:-------------------|----------|---------------|-----------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `limit`            | No       | 10            | No                          | Maximální limit pro stránkovač je 50. Pokud není určen, vrací 10 položek.                                                                                                   |
| `page`             | No       | 1             | No                          | Aktuální stránka.                                                                                                                                                           |
| `workfield_id`     | No       |               | No                          | Array. Filtrace podle ID oborů (profesí). Více v číselníku, viz Enumerations.                                                                                               |
| `office_id`        | No       |               | No                          | Array. Filtrace podle ID poboček.                                                                                                                                           |
| `filter_id`        | No       |               | No                          | Array. Filtrace podle ID jednotlivých filtračních položek přiřazených k inzerátu. Více v sekci filtračních položek.                                                         |
| `channel_id`       | No       |               | No                          | Array. Omezení na určité kanály. Více informací o kanálech vrací číselník, viz sekce Enumerations. Pokud není parametr určen, vrátí se všechny možné inzeráty (dle tokenu). |
| `include_inactive` | No       | 0             | Yes                         | Pokud chcete, aby systém vrátil i pozastavené / staré inzeráty, vložte tento parametr s hodnotou 1.                                                                         |
| `only_deleted`     | No       | 0             | Yes                         | Pokud chcete, aby systém vrátil POUZE smazané inzeráty. V tento moment systém vrátí ale payload pouze s job_id parametrem (payload: [{job_id:1234},{job_id:5678}]).         |
| `status`           | No       | 1             | Yes                         | Parametr se chová jako bitmapa. 1 = aktivní, 2 = neaktivní, 4 = draft, 8 = smazaný. Jsou povolené kombinace všech, krom smazaných, které jdou zobrazit pouze samostatně.    |
|                    |          |               |                             | Status nahrazuje předchozí dva parametry (include_inactive a only_deleted), které jsou deprecated, a při jeho použití jsou ignorovány.                                      | 



Tip: Pokud chcete filtrovat podle adres, můžete inzeráty v Recruitisu přiřadit ke konkrétním pobočkám a pak filtrovat podle nich (u poboček vracíme adresy, pod jednou adresou můžete uvést i více poboček).

#### Requirements

   + Authorization with token
   + token type: `public_access`: pokud se jedná o veřejný inzerát (vystavený na firemních stránkách, xml nebo na pracovních portálech) - (určení dle channel_id).  
   + token type: `full_access`: pokud se jedná o interní inzerát. (určení dle channel_id). 

+ Request
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)

+ Parameters
    + limit (optional,numeric,`10`) - Počet entit, které se mohou zobrazit.
    + page (optional,numeric,`1`) - Strana s výpisem inzerátů.
    + workfield_id (optional,array[int]) - Omezení na určité pracovní obory, profese.
    + office_id (optional,array[int]) - Omezení na určité pobočky, viz sekce Enumerations.
    + filter_id (optional,array[int]) - Omezení na určité filtry, viz sekce Job Filters.
    + channel_id (optional,array[int]) - Omezení na určité kanály, viz sekce Enumerations.
    + include_inactive (optional,boolean) - Vrátí i pozastavené nebo vypršelé inzeráty.
    + only_deleted (optional,boolean) - Vrátí pouze smazané inzeráty, viz Parameters info.

    
+ Response 200 (application/json)

        :[](json/apidoc_jobs_list_get.json)

## Job Detail [/jobs/{id}?{include_inactive}]

### Get Jobs Detail [GET]

 Vrátí detail jednoho inzerátu. Parametry v odpovědi jsou stejné, jako když se vrací více inzerátů najednou.
 
 **POZOR: 18.9.2018 dojde ke změně odpovědi API volání: Inzerát se nebude vracet v payload jako pole (tzn.: nebude `payload: [{...}]`),
 ale bude se vracet přímo daná odpověď (tzn.: `payload: {...}`).**
 
 Pokud daný inzerát neexistuje, vrátí se http status `404` s meta code `api.error.not_found`.


#### Requirements

   + Authorization with token
   + token type: `public_access`: pokud se jedná o veřejný inzerát (vystavený na firemních stránkách, xml nebo na pracovních portálech).
   + token type: `full_access`: pokud se jedná o interní inzerát.

#### Response parameters
   
| Parameter                | token condition | Type          | Note                                                                                                                                               |
|--------------------------|-----------------|---------------|----------------------------------------------------------------------------------------------------------------------------------------------------|
| `job_id`                 | `public_access` | int           | ID inzerátu.                                                                                                                                        |
| `title`                  | `public_access` | string        |                                                                                                                                                    |
| `description`            | `public_access` | string        |                                                                                                                                                    |
| `date_end`               | `public_access` | date          |                                                                                                                                                    |
| `date_created`           | `public_access` | datetime      |                                                                                                                                                    |
| `workfields`             | `public_access` | array(object) |                                                                                                                                                    |
| `workfields` - `id`      | `public_access` | int           |                                                                                                                                                    |
| `workfields` - `name`    | `public_access` | string        |                                                                                                                                                    |
| `stats`                  | `full_access`   | object        | Statistiky k danému inzerátu. Ukazují počty.                                                                                                         |
| `stats` - `flow_answers` | `full_access`   | array(object) | Pole jednotlivých stavů a jejich počtu odpovědí.                                                                                                  |
| `stats` - `answers`      | `full_access`   | int           |                                                                                                                                                    |
| `stats` - `views`        | `full_access`   | int           |                                                                                                                                                    |
| `filterlist`             | `public_access` | array(object) | Seznam filtračních položek.                                                                                                                         |
| `filterlist` - `id`      | `public_access` | int           |                                                                                                                                                    |
| `filterlist` - `name`    | `public_access` | string        |                                                                                                                                                    |
| `filterlist` - `group`   | `public_access` | string        |                                                                                                                                                    |
| `details`                | `public_access` | object        |                                                                                                                                                    |
| `details` - `office_id`  | `public_access` | int           | Pokud je inzerát propojený s pobočkou, tato položka obsahuje ID pobočky (podle ní se dá filtrovat). Pokud není propojená, položka se nezobrazuje. |
| `personalist`            | `public_access` | object        |                                                                                                                                                    |
| `personalist` - `id`     | `public_access` | int           |                                                                                                                                                    |
| `personalist` - `name`   | `public_access` | string        |                                                                                                                                                    |
| `contact` - `name`       | `public_access` | string        |                                                                                                                                                    |
| `contact` - `email`      | `public_access` | string        |                                                                                                                                                    |
| `contact` - `phone`      | `public_access` | string        |                                                                                                                                                    |
| `addresses`              | `public_access` | array(object) |                                                                                                                                                    |
| `addresses` - `id`       | `public_access` | int           |                                                                                                                                                    |
| `addresses` - `city`     | `public_access` | string        |                                                                                                                                                    |
| `addresses` - `psc`      | `public_access` | string        |                                                                                                                                                    |
| `addresses` - `street`   | `public_access` | string        |                                                                                                                                                    |
| `addresses` - `region`   | `public_access` | string        |                                                                                                                                                    |
| `addresses` - `state`    | `public_access` | string        |                                                                                                                                                    |
| `active`                 | `public_access` | bool          | Značí, jestli je Inzerát aktivní (není smazaný ani starý). Pokud se neaplikuje filtr `include_inactive`, tato položka je vždy true.                |
| `draft`                  | `public_access` | bool          | Značí, jestli je Inzerát draft.                                                                                                                    |


+ Request
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)

+ Parameters
    + id (number, `1`) - Job id
    + include_inactive (optional,boolean) - Vrátí inzerát, přestože je pozastavený nebo vypršelý.



+ Response 200 (application/json)

        :[](json/apidoc_jobs_detail_get.json)

        
+ Response 401 (application/json)

        :[](json/apidoc_json_error_401.json)

## Job creation [/jobs]

### Create new job [POST]

Procedura vytvoří nový inzerát a dá ho do rozepsaných. Následně je možné inzerát dokončit přímo v systému Recruitis. Při správném vytvoření se vrátí i odkaz na jeho dokončení.

#### Důležitá informace:
**Při testování POST požadavku v Apiary.io na produkčním serveru: Základní token míří na testovací účet, ke kterému mají přístup i ostatní uživatelé. 
Neposílejte tedy své osobní údaje přes tento token, popřípadě si token změňte na svůj vlastní.**

#### Requirements

   + Authorization with token
   + token type: `full_access`: pro vytvoření inzerátu potřebujeme vždy full access.
   
| Request value                        | Required | Default Value   | Note                                                                                                                                                                                                                           |
|:-------------------------------------|----------|:----------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `title`                              | Yes      |                 | Název pozice.                                                                                                                                                                                                                                |
| `description`                        | Yes      |                 | Popis pozice.                                                                                                                                                                                         |
| `author_id`                          | No       |                 | ID zaměstnance, pod kterým se inzerát založí (pokud není vyplněno, využije se ten, pod kterým je přihlášeno API).                                                                                                                                                                                              |


+ Request (application/json)
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)

    + Body  

            :[](json/apidoc_jobs_post_request.json)

+ Response 201 (application/json)

        :[](json/apidoc_json_post_general.json MSG:"Job was created." CODE:"api.created")
        
+ Response 400 (application/json)
        
        :[](json/apidoc_json_error_general.json MSG:"Can't create job" CODE:"api.error.generic")