# Group Candidates
Kandidát je osoba, kterou máte v databázi a na kterou se vztahují odpovědi.

**Žhaví kandidáti**
Pokud chcete, aby byl uchazeč označen systémem jako "žhavý kandidát", to jest kandidát, 
který je vidět na hlavní stránce, přiložte k němu tag "`tag.hot`". Více o žhavých kandidátech v Recruitisu.

## Candidate entity [/candidates]

### Create new candidate [POST]
Procedura na uložení nového uchazeče. Jako odpověď se vrátí ID kandidáta. 
Vytvoření kandidáta bez odpovědi se hodí například, pokud chcete nabídnout uchazeči možnost vás kontaktovat, ale nemáte pro něj momentálně vhodný inzerát. 

Pokud se vkládá uchazeč, který dle emailu nebo telefonního čísla v systému již existuje, provede se aktualizace informací a vrátí se dané user ID. O všem jste
informování přes meta položku `additional_output`.

#### Requirements

   + Authorization with token
   + token type: `public_access`
   
| Request value                        | Required | Default Value   | Note                                                                                                                                                                                                                           |
|:-------------------------------------|----------|:----------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `name`                               | Yes      |                 |                                                                                                                                                                                                                                |
| `email`                              | No       |                 | Uchazeči se dle emailu slučují.                                                                                                                                                                                                |
| `phone`                              | No       |                 | Uchazeči se dle telefonu slučují.                                                                                                                                                                                              |
| `skype`                              | No       |                 |                                                                                                                                                                                                                                |
| `linkedin`                           | No       |                 |                                                                                                                                                                                                                                |
| `facebook`                           | No       |                 |                                                                                                                                                                                                                                |
| `twitter`                            | No       |                 |                                                                                                                                                                                                                                |
| `strict`                             | No       | false           | Pokud je uvedena hodnotou "1", poté se při nezdaru nahrávání přílohy zastaví celý proces a vrátí se chyba. V opačném případě se uchazeč nahraje s informací, že ne všechno se nahrálo správně (viz `meta.additional_output`) . |
| `gdpr_agreement`                     | Yes      |                 | GDPR souhlas uchazeče o správě jeho osobních informací. Bez souhlasu není možné uchazeče importovat.                                                                                                                           |
| `gdpr_agreement` - `date_expiration` | No       | 1 year from now | formát YYYY-MM-DD                                                                                                                                                                                                              |
| `gdpr_agreement` - `source`          | No       | "manual"        | Stringové označení, odkud byl GDPR souhlas pořízen.                                                                                                                                                                            |
| `attachments`                        | No       |                 | Velikost souboru nesmí přesáhnout 3MB.                                                                                                                                                                                         |
| `attachment` - `path`                | Yes      |                 | Atribut `path` nebo `base64` je vyžadován. Ujistěte se, že je soubor dostupný z jiné domény.                                                                                                                                   |
| `attachment` - `base64`              | Yes      |                 | Atribut `path` nebo `base64` je vyžadován. Data souboru vs base64 formátu.                                                                                                                                                     |
| `attachment` - `filename`            | Yes      |                 | Název souboru. Musí obsahovat koncovku a čitelný znaky. Mezery budou nahrazeny podtržítkem.                                                                                                                                    |
| `attachment` - `type`                | No       | 1               | @see Enumeration section                                                                                                                                                                                                       |
| `extra`                              | No       |                 | Pole objektů, které přiřadí k odpovědi poznámku, nebo tag.                                                                                                                                                                     |
| `extra` - `note`                     | Yes      |                 | Atribut `note` nebo `tag` je vyžadován. Pokud je určeno, uloží se hodnota jako poznámka. **Maximální délka poznámky je 800 znaků**                                                                                             |
| `extra` - `tag`                      | Yes      |                 | Atribut `note` nebo `tag` je vyžadován. Pokud je určeno, uloží se hodnota jako tag k uchazeči. **Maximální délka poznámky je 100 znaků**                                                                                       |


+ Request (application/json)
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)

    + Body  

            :[](json/apidoc_candidates_post_request.json)

+ Response 201 (application/json)

        :[](json/apidoc_json_post_general.json MSG:"Candidate was created." CODE:"api.created")
        
+ Response 400 (application/json)
        
        :[](json/apidoc_json_error_general.json MSG:"Can't upload attachment." CODE:"api.error.generic")
        
        
### Delete candidate [DELETE /candidates/{id}]

Toto volání smaže kompletně daného uchazeče a všechny informace, které jsou k němu přidruženy. 
Všechny jeho odpovědi, pohovory, poznámky, přílohy, GDPR souhlasy atd. **Takto smazaný uchazeč se již nedá jakkoli obnovit.**

Na toto volání se vztahuje denní kvóta. V případě překročení denní kvóty se vrátí odpověd `403 - forbidden` s `meta.code` `api.error.quota.exceeded`

+ Parameters
     + id (required, number, `1`) - ID kandidáta (user ID)

    
+ Response 200 (application/json)

                :[](json/apidoc_json_response_empty_general.json MSG:"User was deleted." CODE:"api.deleted")
        
+ Response 404 (application/json)
        
        :[](json/apidoc_json_error_general.json MSG:"User ID XXX doesn't exists." CODE:"api.error.not_found")

+ Response 403 (application/json)
        
        :[](json/apidoc_json_error_general.json MSG:"Daily 'quota_candidates_delete quota' has been exceeded." CODE:"api.error.quota.exceeded")


## Answer list [/answers]

Odpověď patří pod entitu kandidáta. Pokud si to máme relačně představit, máme vztah mezi kandidátem a odpovědmi je 1:N. V této sekci se podíváme na získávání odpovědí. 

### Create new answer [POST]
Procedura na uložení nové odpovědi. Jako odpověď se vrátí ID odpovědi. Při vytváření odpovědi se vytvoří i nový uchazeč, pokud již s danými kontakty (email, telefon) neexistuje.
V druhém případě se přiřadí k již existujícímu.

API nepodporuje vložení duplikátních odpovědí. Pokud (dle emailu nebo telefonu) již uchazeč
na daný inzerát odpovídal, vrátí se jeho answer ID s kódem: `meta`.`code` = `api.unmodified`

Poznámka: Souhlas se zpracováním osobních údajů dostává takto vytvořená odpověď automaticky. Její platnost je v základním nastavení 1 rok. Pokud byste si přáli toto nastavení změnit, kontaktujte nás. 

#### Requirements

   + Authorization with token
   + token type: `public_access` : pokud se jedná o veřejný inzerát (vystaven na firemních stránkách,xml nebo na pracovních portálech)
   + token type: `full_access` : pokud se jedná o interní inzerát.    
   
| Request value                        | Required | Default Value   | Note                                                                                                                                                                                                           |
|:-------------------------------------|----------|:-:--------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `job_id`                             | Yes      |                 |                                                                                                                                                                                                                |
| `name`                               | Yes      |                 |                                                                                                                                                                                                                |
| `email`                              | No       |                 |                                                                                                                                                                                                                |
| `phone`                              | No       |                 |                                                                                                                                                                                                                |
| `skype`                              | No       |                 | Odkaz na uchazečův Skype                                                                                                                                                                                       |
| `linkedin`                           | No       |                 | Odkaz na uchazečův LinkedIn                                                                                                                                                                                    |
| `facebook`                           | No       |                 | Odkaz na uchazečův Facebook                                                                                                                                                                                    |
| `twitter`                            | No       |                 | Odkaz na uchazečův Twitter                                                                                                                                                                                     |
| `source_id`                          | No       | -1              | Zdroj, odkud odpověď přišla. Více u volání `GET \enums\sources`                                                                                                                                                |
| `source`                             | No       |                 | String. Zdroj odpovědi, který se automaticky vytvoří (tudíž není potřeba znát jeho ID.) Pokud již zdroj existuje, přiřadí se k existujícímu. Tato položka je **ignorována** pokud je udána hodnota `source_id` |
| `referral_id`                        | No       |                 | ID referrala (ID získané z Recruitis referral stránky, API pro referraly je v plánu)                                                                                                                           |
| `cover_letter`                       | No       |                 |                                                                                                                                                                                                                |
| `gdpr_agreement`                     | No       |                 | Pokud je objekt uveden, k odpovědi se přidá i GDPR souhlas o zařazení do databáze uchazečů pro danou firmu.                                                                                                    |
| `gdpr_agreement` - `date_expiration` | No       | 1 year from now | formát YYYY-MM-DD                                                                                                                                                                                              |
| `gdpr_agreement` - `date_created`    | No       | now             | formát YYYY-MM-DD H:i:s                                                                                                                                                                                        |
| `gdpr_agreement` - `source`          | No       | "manual"        | Stringové označení, odkud byl GDPR souhlas pořízen.                                                                                                                                                            |
| `attachments`                        | No       |                 | Velikost souboru nesmí přesáhnout 3MB.                                                                                                                                                                         |
| `attachment` - `path`                | Yes      |                 | Atribut `path` nebo `base64` je vyžadován. Ujistěte se, že je soubor dostupný z jiné domény.                                                                                                                   |
| `attachment` - `base64`              | Yes      |                 | Atribut `path` nebo `base64` je vyžadován. Data souboru vs base64 formátu.                                                                                                                                     |
| `attachment` - `filename`            | Yes      |                 | Název souboru. Musí obsahovat koncovku a čitelný znaky. Mezery budou nahrazeny podtržítkem.                                                                                                                    |
| `attachment` - `type`                | No       | 1               | @see Enumeration section                                                                                                                                                                                       |
| `extra`                              | No       |                 | Pole objektů, které přiřadí k odpovědi poznámku, nebo tag.                                                                                                                                                     |
| `extra` - `note`                     | Yes      |                 | Atribut `note` nebo `tag` je vyžadován. Pokud je určeno, uloží se hodnota jako poznámka. **Maximální délka poznámky je 800 znaků**                                                                             |
| `extra` - `tag`                      | Yes      |                 | Atribut `note` nebo `tag` je vyžadován. Pokud je určeno, uloží se hodnota jako tag k uchazeči. **Maximální délka poznámky je 100 znaků**                                                                       |

**GDPR a souhlas se zpracováním osobních údajů k dané pozici:**
Pokud není určen GDPR souhlas, tak souhlas ke zpracováním os. údajů dostává uchazeč k dané pozici vždy automaticky na rok, popř. do skončení pozice. Jako zdroj souhlasu se uvádí "api". 
Pokud GDPR souhlas určen je, tak souhlas ke zpracováním os. údajů dědí jeho zdroj a také datum expirac (Maximálně ale na rok.).  

+ Request (application/json)
    + Headers
    
            Authorization: Bearer :[](apidoc_bearer_token.txt)

    + Body  
    
            :[](json/apidoc_answers_post_request.json)

+ Response 201 (application/json)

        :[](json/apidoc_answers_post_response.json)
        
+ Response 400 (application/json)
        
        :[](json/apidoc_json_error_general.json MSG:"Can't upload attachment." CODE:"api.error.generic")
