#Group Me

## My account information [/me]

### Me [GET]

Získání informací o práce přihlášeném účtu.

+ Request
    + Headers

            Authorization: Bearer 68b0c063374ac7fe0abaa18342dbad23168876a1.8699.3e398f0ccd4c857b29de10397534afac

+ Response 200 (application/json)

        {
            "payload": {
                "fullname": "Michal Macinka",
                "email": "macinka@gmail.com",
                "img_src": "http://lide.uhk.cz/fim/student/macinmi1/avatar_2.jpg",
                "device_id": "x56sj64uzr4we64rtb489uzjj186drgv13e",
                "device_name": "restapiklient"
            },
            "meta": {
                "duration": "2259.39",
                "total_duration": 2300,
                "code": 200,
                "message": "",
                "message_localized": "OK"
            }
        }

+ Response 401 (application/json)

        :[](json/apidoc_json_error_401.json)